### ISSUE TITLE
Cheat Error

### ISSUE THREAD

**Issue by Mitsolaos** [Jire/Charlatano#10]
Hi Jire 

after a few seconds with cheat on there is a java error here's a link
http://imgur.com/a/8fRj4

and in console are those errors pop up
http://imgur.com/a/dGaRb

which update shall i use for it to work properly or maybe do i miss another prog or smthing 

ty

**Comment by Jire** [comment]
Hey, do you happen to have recently updated your NVidia driver to version 378.49?

**Comment by Mitsolaos** [comment]
yes jire that's my NVidia driver version right now ok i will but shall u also include links with java version u run now on ur pc ty

**Comment by Jire** [comment]
@Mitsolaos You can rollback to an older driver by downloading and installing this: http://www.nvidia.com/download/driverResults.aspx/113448/en-us

**Comment by Mitsolaos** [comment]
yeah yeah i am downloading them right now, i hope it will work fine i will keep u update

**Comment by Mitsolaos** [comment]
@Jire well it worked for a while plus bhop not error with java but in console after a while are all those errors

http://imgur.com/a/rhvNa

**Comment by Mitsolaos** [comment]
@Jire any help with these stuff http://imgur.com/a/rhvNa

**Comment by Jire** [comment]
@Mitsolaos Try the new version, https://github.com/Jire/Charlatano/releases/tag/0.9.5
