### ISSUE TITLE
Will i be ban when i ask this stupid question:D?

### ISSUE THREAD

**Issue by minegrass** [Jire/Charlatano#100]
Why this cheat is undetected
And how it do it
and is it VAC safe??:::D:D:D:D:

Tell me lemme know and lemme feel safe :+1:

**Comment by Alexw0wTV** [comment]
its safe i used this for 3 moths

**Comment by Rorky** [comment]
You sound like your trying to make shitty cheats and copying Jire so you don't have to  :)))

**Comment by DirtySenpai** [comment]
It's undetected because valve hasn't been assed to add the signature. It could easily be in about 2 minutes of work.
