### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by neckztik** [Jire/Charlatano#1001]
I get this error after Charlatano opens, I don't know how to fix this.

https://i.imgur.com/gbC8ln7.png

**Comment by hondazo** [comment]
Try to switch to an older version.

**Comment by jackieyiwu** [comment]
> 
> 
> I get this error after Charlatano opens, I don't know how to fix this.
> 
> https://i.imgur.com/gbC8ln7.png

i got it too

**Comment by ruper3734** [comment]
me too
