### ISSUE TITLE
0.98

### ISSUE THREAD

**Issue by Alexw0wTV** [Jire/Charlatano#104]
Can i use 0.98...  to they fix aimbot to 1.0.0

**Comment by kominxe** [comment]
1.0.0 aimbot working fine

**Comment by Alexw0wTV** [comment]
not for me

**Comment by Alexw0wTV** [comment]
or glow

**Comment by ibbizaki123** [comment]
in current ver1.0.0  aimbot not working nor glow

**Comment by Alexw0wTV** [comment]
so can i use 0.98 without ban?

**Comment by kominxe** [comment]
@ibbizaki123 m8 for me it's working i can compile it for u
@Alexw0wTV i think u can

**Comment by Alexw0wTV** [comment]
na i cant in current ver1.0.0 aimbot not working nor glow

**Comment by Sababdb** [comment]
Hey can anyone teach me how to use the cheats, 0.9.8, I wanna use it but the files has changed and its like, Builder, run and other stuff, im not sure what to do? any help or send file

**Comment by ibbizaki123** [comment]
@kominxe  how it is working dude i compiled 2-3 times but it didnt work for me ? is there any thing in settings ?

**Comment by ibbizaki123** [comment]
![image](https://cloud.githubusercontent.com/assets/15956995/25616388/abfac418-2f55-11e7-8a94-97b670772593.png)

**Comment by Jire** [comment]
![](http://i.imgur.com/KHdGtQX.png)
![](http://i.imgur.com/lv4Buq3.png)

**Comment by xrtd108** [comment]
Everything except aim & RCS work for me. I am building the correct way. Don't use trigger so I haven't tried that. 
Idk if it has anything to do with :processResources NO-SOURCE but Jire disregarded that so I doubt it.

**Comment by ibbizaki123** [comment]
@Jire i found on discord vac detects this hack is it true ??
