### ISSUE TITLE
Hack detected CEVO And Faceit

### ISSUE THREAD

**Issue by psxsahan** [Jire/Charlatano#107]
Hack detected CEVO And Faceit

**Comment by DeathStrax** [comment]
Really? can confirm?

So then, is it VAC-detected?

**Comment by Jire** [comment]
Incorrect, you need to read before using something.

**Comment by psxsahan** [comment]
yes i can confirm.i was use only aimbot lol :D its vac safe but not enough at cevo and faceit.

**Comment by Jire** [comment]
You must use path aimbot, the default aimbot will get you banned.
