### ISSUE TITLE
Bypass GamersClub Anticheat...Is there a way?

### ISSUE THREAD

**Issue by ricabook** [Jire/Charlatano#112]

**Comment by DirtySenpai** [comment]
GamersClub anticheat is easyanticheat. Find yourself an EAC bypass and you'll be fine.

**Comment by ricabook** [comment]
Man! No idea what you are talking about. =(
Could you help me?
Thank you very much!

**Comment by jonesdj1** [comment]
No

**Comment by Rorky** [comment]
skiddddddddddd

**Comment by DirtySenpai** [comment]
afraid not @ricabook you'd be better served by buying a private cheat with EAC support, or try leaguecheats, I think they were advertising eac support, not sure though.

**Comment by ricabook** [comment]
Ok! Thank you!!

**Comment by ricabook** [comment]
@DirtySenpai Any thoughts about the new CSGO update? Charlatano just stopped working.

**Comment by DirtySenpai** [comment]
@ricabook about four minutes of work for anyone who can be assed to update it.

**Comment by ricabook** [comment]
Really?? OMG....So.. Just waiting... 
Tks again!

**Comment by mountaser** [comment]
@ricabook  https://github.com/G-E-N-E-S-I-S/FuckBattlEye

**Comment by ricabook** [comment]
Great @mountaser ! Just downloaded the files. Could you help me installing? Thank you!!

**Comment by Rorky** [comment]
holy shit you don't that what visual studios is rica

kys pls thxxx

**Comment by ricabook** [comment]
I'm sorry @Rorky ... Really noob at this stuff... I just need to past the files at the game folder? Thank you!!!

**Comment by jonesdj1** [comment]
kys ur soo dumb

**Comment by ricabook** [comment]
Just trying to learn, @jonesdj1 . You asshole.
