### ISSUE TITLE
Update for Charlatano.

### ISSUE THREAD

**Issue by DeathStrax** [Jire/Charlatano#120]
Please update Charlatano for the recent update on CSGO (13/5/17).

Probably you have been busy...but please try to spend some time on this.

Appreciate it.

**Comment by Rorky** [comment]
lol

update offsets yourself if you have that attitude

**Comment by DeathStrax** [comment]
Is there anyway to update offsets? Im not sure how....

**Comment by Rorky** [comment]
yes but its differently coded

check my issue thread called "Offsets" there is a directory and someone pasted a link to the newest offsets.
