### ISSUE TITLE
a

### ISSUE THREAD

**Issue by Balouchis** [Jire/Charlatano#121]

**Comment by Rorky** [comment]
i hope you snap your neck because your so retarded. another 5 issues about this being broken

just wait until offsets are updated

pls stop this shit

**Comment by Balouchis** [comment]
[ MISC ]
– Fixed a bug that caused knife swings to do reduced damage in the 0.4 seconds after their deploy animation finished, as if you had just taken a swing. (Sorry Snax!)
– Fixed snd_legacy_surround settings.
– Fixed round start music continuing to play if player walked out of buy zone.
– HTTP logger now includes server token header, and precise time on log lines.
– Fixed a regression in command routing code to automatically allow cheat-protected commands on cheat-enabled servers.
– Marked snd_playsounds command as cheat.
– Whitelisted about:blank URL for MOTD
– Upgraded Windows compile toolchain for Windows client and dedicated server binaries
– Fixed long standing issue with lightstyles and dynamic shadow blending – they are now compatible with CSM’s and can be used in maps.
[ PERFECT WORLD ]
– Localization update for various UI elements.
– Localization updates for several in-game textures and Weapons Course map.
– Added purchasing flow using Perfect World balance.
This the new update csgo. Does anyone of them can cause charlatan not to work? I think maybe windows compile tool may be causing it to not work ?

**Comment by Rorky** [comment]
i really hope your blind because your are retarded.

**Comment by DeathStrax** [comment]
Please close this Issue
