### ISSUE TITLE
Offset pattern changed

### ISSUE THREAD

**Issue by DeathStrax** [Jire/Charlatano#122]
So, can 0.9.8 version stilll be used, considering the offset pattern was changed, or will I have to build a new one from the current 1.0.0 version

**Comment by Rorky** [comment]
ready to hang myself kiddo

**Comment by Rorky** [comment]
time to be nice.

rebuild charlatano > copy your settings from outdated offset charlatano > go to new offset charalatano and paste your settings into new charalatano.

**Comment by DeathStrax** [comment]
You managed to do it? Or is this hypothetical?

**Comment by Rorky** [comment]
pardon my asshole attitude

i rebuilt charala (keep in mind fresh build) and it won't load properly. i'll try and figure out xd

**Comment by DeathStrax** [comment]
All good. I have been using this hack for a long time... but I have not experience in coding...., so I appreciate your help.
