### ISSUE TITLE
Error with SafeAim and WriteAim

### ISSUE THREAD

**Issue by DeathStrax** [Jire/Charlatano#124]
@Jire 
![image](https://cloud.githubusercontent.com/assets/26869694/26044440/b29c3216-3987-11e7-99b1-6ba93aa71ad3.png)
Built the .bat file and started in-game. Came out with this error, and the hacks not working (even esp). 

Maybe the cheat is still not ready, I am not sure. Just pointing it out.

**Comment by BrunoSammartino** [comment]
Its not a problem! Bro Just update the Java and Unzip the file again and do nothing with settings. It will work fine then.

**Comment by DeathStrax** [comment]
update the java? unzip the file?

There is nothing to update and nothing to unzip. I built the hack from build.bat.....

**Comment by DeathStrax** [comment]
I will try though
