### ISSUE TITLE
hey anyone mind helping me out here?

### ISSUE THREAD

**Issue by HeBosco** [Jire/Charlatano#126]
hey so I'm trying to run the build.bat on the latest version and it fails, here's what it says. anyone know how to fix it?
e: Compiler terminated with internal error                                      :compileKotlin FAILED                                                                                                                                           FAILURE: Build failed with an exception.                                                                                                                        * What went wrong:                                                              Execution failed for task ':compileKotlin'.                                     > Internal compiler error. See log for more details                                                                                                             * Try:                                                                          Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.                                                                                                                                  BUILD FAILED

**Comment by anurag01021996** [comment]
First thing- update jdk to latest version and set java_home path correctly
Second thing- even if you become successful in compiling ....still it won't
work....others have already tried ...
Update is in progress...so keep calm...bro :)

**Comment by HeBosco** [comment]
ok thanks  for the info
