### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by skatanas** [Jire/Charlatano#13]
Hi @Jire 

well i got this issue while i run the cheat everything seems legit till after a few secs in console all those errors pop up http://imgur.com/a/rhvNa

any idea of solution?

**Comment by Jire** [comment]
Please try the new version: https://github.com/Jire/Charlatano/releases/tag/0.9.5

Let me know if your problem is resolved! :smiley:

**Comment by skatanas** [comment]
ty for reply @Jire 

gosh i feel like a girl using a pc for the 1st time knowing nothing well now there's this pop up

https://i.imgsafe.org/4c703c3759.jpg

how to use the command xskip runtime?

**Comment by jonesdj1** [comment]
@skatanas overlay error hmm maybe try turning it off

**Comment by skatanas** [comment]
@jonesdj1 well if you mean OpenGL overlay my settings are 

opengl_fps=60 moninot at 60 mhz
OPENGL_VSYNC = false don't want to use VSync in my games
OPENGL_MSAA_SAMPLES = 0 as much antialising

if i am off the point then i need ur help

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/0.9.7
