### ISSUE TITLE
New Features?

### ISSUE THREAD

**Issue by DeathStrax** [Jire/Charlatano#133]
Hi @Jire ,

I would like a thank you for your work in creating this CSGO hack for the community. 

I was wondering if adding new features would be a possibility for this programming language you code this hack in.

The features that I hope to see in the future are:

1) Silent aim, determined by FOV, for AWP and Scout. 
For example if you set the FOV to 2, even if you are not aiming directly at the enemy, you still get to pull the shot off. So that it looks like you flicked the shot and got the enemy.

2) Crosshair for Snipers and Auto-Snipers.
I believe this would be perfect for allowing a quick scope and easy adjustment to the aim. I am a noob at sniping, so yeah...

That is all. 

PS. Thanks for updating Charlatano.

Thank you for reading this.

**Comment by Jire** [comment]
Yes these features are both possible but I will most likely add #2 first :stuck_out_tongue_winking_eye:

**Comment by DeathStrax** [comment]
Nice. 

1 Issue though with 1.0.2.

I am not sure what I am doing wrong, but when I built Charlatano 1.0.2 and started CSGO and the hack, nothing happened.

I enabled ESP, RCS and AIM. No luck. New offsets maybe?
