### ISSUE TITLE
Charlatano 1.0.2 Features Working or not?

### ISSUE THREAD

**Issue by DeathStrax** [Jire/Charlatano#134]
1. ESP is not working. Why? There is not outline of the enemy or team.

2. RCS is working.

3. AIM is not working. 

4. Bunnyhop (Unsure, never used it)

5. NoFlash (Unsure, never used it)

6. BoneTrigger (Unsure, never used it)

If anyone has them working, please tell me what I am doing wrong.

Thanks

**Comment by Jire** [comment]
Please post your console errors

**Comment by DeathStrax** [comment]
Hm, I did not have console errors.

**Comment by punkjj** [comment]
@Jire Offsets / sigs are still outdated. nothing seems to work for me, no errors.

**Comment by punkjj** [comment]
RCS is working but its too broken

**Comment by Balouchis** [comment]
I don't know why its not working for you but its working for me fine! :( 👍
