### ISSUE TITLE
Charlatano 1.0.2 - Gray screen on startup

### ISSUE THREAD

**Issue by xyzVyrus** [Jire/Charlatano#140]
Evening fellow readers,

Upon opening Charlatano 1.0.2, with completely unedited scripts, after a few seconds my entire screen turns gray. I'm able to see the ALT + TAB selection menu, but tabbing into _any_ program will still cause my screen,  **taskbar and all** to turn gray. The only option that I have found for fixing this without a restart or logout, is to close "Start Charlatano 1.0.2" from the ALT + TAB selection menu. I do in fact have the latest build of Java. **( Java SE Development Kit 8u131)**

_(I'm not able to see the error in the Charlatano console because once tabbed back in, the screen remains gray, thus I do not know the exact error)_

If anyone has a solution to my problem, I kindly ask that you share (:

It is in fact okay is an exact answer is not given, I understand that you, as a developer, happen to be very busy after a new release.

Thank you very much!

**Comment by Semper-r** [comment]
It just happened to me when i didnt switchback to counter before charlatano completely starts so switch back to the counter window fast
