### ISSUE TITLE
USB or HDD

### ISSUE THREAD

**Issue by ricabook** [Jire/Charlatano#141]
Hello guys,

Should i run Charlatano from USB Flash Drive or Hard Drive?

Thank you,

PS: All settings working fine for me with Carlatano 1.02

**Comment by M4jx** [comment]
It doesn't matter.
If it did the developer would have mentioned it before.

**Comment by mountaser** [comment]
@M4jx  take a look at my repo in 5min

**Comment by ricabook** [comment]
@M4jx Thank you!
