### ISSUE TITLE
Change AWP aim button

### ISSUE THREAD

**Issue by ricabook** [Jire/Charlatano#143]
Hello guys,
I'm wondering if i can change the AWP aim button. In the "Aim.kts" settings i saw "force aim button". Is this the button i need to change? Can i use any button of the Virtual Key Codes (i want to use Shift, so number 10) ??

Thank you,

**Comment by trolloos** [comment]
shift is number 16

http://cherrytree.at/misc/vk.htm

**Comment by ricabook** [comment]
Thank you, @trolloos!!
