### ISSUE TITLE
Change Bone

### ISSUE THREAD

**Issue by ricabook** [Jire/Charlatano#148]
Hello guys,

Is it possible to change the main bone (head) of aimbot? I'm not talking about triggerbot... It's the aimbot i want to change.

I believe that changing the bone to shoulder would make Charlatano even more legit.

Thank you again!

Rgds

**Comment by trolloos** [comment]
In general settings go to 

/**
 * The bone IDs of the respective bones for a player.
 *
 * The left-side number is for CS:CO, and the right-side number is for CS:GO.
 */
HEAD_BONE = if (CLASSIC_OFFENSIVE) 6 else 8
SHOULDER_BONE = if (CLASSIC_OFFENSIVE) 5 else 7
BODY_BONE = if (CLASSIC_OFFENSIVE) 4 else 6

and just change head_bone to the shoulder bone I think that should work

**Comment by ricabook** [comment]
It worked!
Again, thank you very much, @trolloos !!

Rgds
