### ISSUE TITLE
Nothing happens.

### ISSUE THREAD

**Issue by jankastel** [Jire/Charlatano#15]
Sup,

When It finishes with the download it opens, but nothing happens..just a blank cmd window(can't type in it)
so nothing changes in-game

I've got windows 10(latest java sdk, the download gave no errors)

Any help would be greatly appreciated﻿

**Comment by Z0ckerchris** [comment]
The window is supposed to be blank. Just wait a bit until it loads. You may need to be ingame and alive for it to work properly.

**Comment by jankastel** [comment]
Ye, I know it's supposed to be blank. But even with all the waiting nothing happens..dunno

**Comment by jonesdj1** [comment]
@jankastel retry running it as administrator

**Comment by jankastel** [comment]
@jonesdj1 Already tried but it gives an error "Error: Unable to access jarfile Charlatano 0.9.5.jar"

**Comment by Jire** [comment]
@jankastel Please email me (TeamViewer)[https://teamviewer.com] details so I can take a look, thomasgnappo@gmail.com
