### ISSUE TITLE
Screen flickering

### ISSUE THREAD

**Issue by StickyPenis** [Jire/Charlatano#152]
I have used this cheat for some time now and it's an amazing cheat, never had any issues with it.
The newest version, 1.0.2, is working fine for me.

But when i loaded up the game with the new version, i noticed a very annoying screen flickering (fullscreen, 16:10 resolution) and it just won't stop.
I have never had this issue with previous versions.
I played around with the settings for a bit, but I couldn't find a solution.

Does it have to do with certain graphic settings? I only use the flat aimbot, nothing else.
If it has something to do with my resolution, refresh rate, graphics settings or Charlatano settings, please let me know.

Thanks in advance!

Edit: This has been going since 1/2 days before the update!

**Comment by Jire** [comment]
Try out the latest release [1.0.3](https://github.com/Jire/Charlatano/releases/tag/1.0.3).

**Comment by StickyPenis** [comment]
Still didn't fix it for me, is there anything I can do?
