### ISSUE TITLE
Config for rage aim

### ISSUE THREAD

**Issue by viniciuspwd** [Jire/Charlatano#153]
First, that's a great public cheat, congrats! 

How can I configure the Aim and Trigger to a rage mode? Even I activating the Perfect AIM, sometimes the lock fail.

Thanks :)

**Comment by Semper-r** [comment]
you should read the kts files and figure it out yourself is not hard to read a couple of pages mate, and the lock and trigger may sometimes fail due to ping but that is obvious

**Comment by Semper-r** [comment]
i mean asking for that is like asking your room-mate to put your shoes on you, it doesnt feel very good if someone asks you something like that, know what i mean?

**Comment by kokolino1** [comment]
wait...is the cheat working perfectly for you ?

**Comment by Semper-r** [comment]
rage aim is almost working perfectly

**Comment by adxjml** [comment]
how about your wallhack?

**Comment by Semper-r** [comment]
for the esp, it only works correctly the glow

**Comment by viniciuspwd** [comment]
what are your video configs when you use the glow? @Semper-r
