### ISSUE TITLE
Cheat wont work ingame

### ISSUE THREAD

**Issue by mind0r** [Jire/Charlatano#16]
Hey Jire, i followed every single step you made on the tuttorial, i've even changed on esp settings to skeleton and boxes true and glow false, but it wont work anyway.. I first opened the game with ak in hand then clicked on charlatano
![ch3](https://cloud.githubusercontent.com/assets/25549035/22619088/3c02be46-eae4-11e6-8a9b-a1ce09439a46.jpg)

after everything downloaded it become like this
![ch2](https://cloud.githubusercontent.com/assets/25549035/22619095/6b521fd4-eae4-11e6-94bf-85c92b9f2a4d.jpg)

after i went into the game and there was nothing changed, no esp, no box, and the aim does nothing too tried mouse5 and so on.

I even closed and turned it on again and it happears like this
![ch4](https://cloud.githubusercontent.com/assets/25549035/22619100/a1bdd28e-eae4-11e6-9d90-0c74e4a6bb1a.jpg)

I dont know if there is any error
I really would like to use it, hope you can help me.
Thanks and keep up the good work!
PS: I added you on skype, so when you have time ;)

**Comment by pakboy** [comment]
Need to Fix The high usage  and crash the game 👎 
Soo Much lagg When the Starting the game 👎

**Comment by mind0r** [comment]
well i dont crash, the cheats just dont show up :/ after cmd loads

**Comment by pakboy** [comment]
restart your Pc restart your game Hope you Fix it 👍

**Comment by mind0r** [comment]
i've tried restart several times multiple times , still wont work, everything goes like i post it, in-game there is nothing different :/

**Comment by Jire** [comment]
You can't run CS:GO nor Steam as admin. Perhaps that is the issue 👍

**Comment by mind0r** [comment]
i dont  think i have steam or csgo with  admin rights but will test it out now, thanks for the fast reply :+1:

**Comment by mind0r** [comment]
Jire i did as you said, launched everything without administrator rights, but still it wont work, i noticed on the middle of the batch execution this transfer fail
![trfailed](https://cloud.githubusercontent.com/assets/25549035/22620935/3590c7ee-eb0f-11e6-8ca8-cc605f447523.jpg)
at the end it seems to be ok as the last screenshot on first post, but it wont work nothing in-game, i have windows7 ultimate 64bit, also tried on windows7 home basic 64. still don't work. Is there anyway you can help me out?

**Comment by mind0r** [comment]
Just added you on steam Jire

**Comment by mind0r** [comment]
Fixed! thanks Jire

**Comment by Krouzu** [comment]
> You can't run CS:GO nor Steam as admin. Perhaps that is the issue 👍
 
This might be my problem lol

**Comment by skatanas** [comment]
@mind0r how did you manage to fix it i got somehow the same console errors

**Comment by mind0r** [comment]
well i did put windows 10, my windows was fulled of virus, i think it might fail on win7

**Comment by skatanas** [comment]
@mind0r that's weird i am on windows 10 enterprice but i have the errors, well it might be karpesky blocking files or i don't know i will check it later

**Comment by mind0r** [comment]
if you get the errors try to go at appdata > local > capsules, and delete those folders and try to run again

**Comment by skatanas** [comment]
@mind0r  nothing changed

**Comment by mind0r** [comment]
@skatanas well i update for new nvidia hotfix, if you get java error try this, https://nvidia.custhelp.com/app/answers/detail/a_id/4378

**Comment by Mitsolaos** [comment]
@mind0r hmmm still got the errors i don't know

**Comment by keepo1337** [comment]
@mind0r @Mitsolaos the cheat usually still works like this. I tried disabling (actually uninstalling) my antivirus and I disabled my firewall just to look if it works now. And... It works just fine.
