### ISSUE TITLE
BombTimer isn't visible at all?

### ISSUE THREAD

**Issue by punkjj** [Jire/Charlatano#17]
I enabled it in scripts, but it isn't visible even after planting bomb or whatever. I'm playing CS:GO at 1024x768 | Stretched | Full-Screen mode. Box ESP and Skeleton ESP isn't visible too ):

**Comment by Jire** [comment]
You cannot use fullscreen mode if you want to see any of the OpenGL overlay stuff (box/skeleton ESP, and bomb timer).
