### ISSUE TITLE
charlatano on zengaming ?

### ISSUE THREAD

**Issue by anurag01021996** [Jire/Charlatano#172]
does charlatano bypass the easy anti cheat client of zengaming on zengaming leagues?   @Jire

**Comment by Semper-r** [comment]
doesnt really matter, if you win something they will review all your matches (by demo) or if someone flags you.

**Comment by anurag01021996** [comment]
Actually it didn't work...I tried :/

**Comment by punkjj** [comment]
You need to bypass EAC manually.

**Comment by anurag01021996** [comment]
@punkjj can u explain a bit?
