### ISSUE TITLE
Inefficient bunnyhop script scroll method

### ISSUE THREAD

**Issue by Veylkar** [Jire/Charlatano#18]
Replace `robot.mouseWheel(if (randBoolean()) amount else -amount)` in BunnyHop.kt with `mouseWheel(if (randBoolean()) amount else -amount)`

Add `fun mouseWheel(Amount: Int) = CUser32.mouse_event(MOUSEEVENTF_WHEEL, 0, 0, Amount, 0)` to Mouse.kt

**Comment by Jire** [comment]
https://github.com/Jire/Charlatano/commit/c9b3478b72f0694405d562401809bea035122eeb
