### ISSUE TITLE
Build problem pls help

### ISSUE THREAD

**Issue by hornyvader** [Jire/Charlatano#191]
pls  help me 

http://imgur.com/uedtdiZ

**Comment by viniciuspwd** [comment]
Try to uninstall your current JDK version and update that to the [most recent version](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html).

**Comment by hornyvader** [comment]
nope still same

**Comment by hornyvader** [comment]
thanks it worked
