### ISSUE TITLE
Anticheaters

### ISSUE THREAD

**Issue by viniciuspwd** [Jire/Charlatano#195]
Can I use this cheat on FaceIT, ZenGaming or GamersClub? Is it safe to ban in those anticheaters?

**Comment by Jire** [comment]
If using path aim it is safe on all those.

**Comment by ricabook** [comment]
@Jire But how can we bypass the AC?

**Comment by StickyPenis** [comment]
@Jire When i use pathaim at the same speeds as flat aim, it is really, really fast. 
Do i lower the speeds or do i enhance another setting i missed somewhere?
