### ISSUE TITLE
The screen goes black after a few seconds

### ISSUE THREAD

**Issue by 2precise4you** [Jire/Charlatano#197]
The screen goes black after a few seconds but I can interact with things in the background, wich I dont see , and when I close the CMD, it all goes back to normal,

**Comment by ikrypt0** [comment]
if you have reduced flash on, fix the alpha by raising it and i would recommend not using the box or skeleton esp

**Comment by 2precise4you** [comment]
Or, can I disable reduced flash, because I dont really need it ?

**Comment by ikrypt0** [comment]
well for me the main problem was the skeleton and box esp, so you can disable reduced flash

**Comment by 2precise4you** [comment]
Yup, disabled Skeleton,box esp and reduced flash and it is working just fine, thanks m8
