### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by 2precise4you** [Jire/Charlatano#205]
It doesnt work anymore, it doesnt show the esp, aim doesnt work, it worked yesterday, so please help.

**Comment by vovashahov** [comment]
all work fine for now. try reinstall cheat

**Comment by 2precise4you** [comment]
Nope, still doesn`t work

**Comment by RichHammond** [comment]
I'm having the same problem. My aimbot is working sometimes, and the ESP is flickering and sometimes not working at all.

**Comment by ricabook** [comment]
Working fine here.
Win 10 and latest java updates.

**Comment by 2precise4you** [comment]
How do I update the drivers ?
