### ISSUE TITLE
CSGO update, Hack no longer works for me

### ISSUE THREAD

**Issue by YourFutureBoyfriend** [Jire/Charlatano#218]

**Comment by ricabook** [comment]
Please @Jire , Update the cheat for us!

**Comment by RichHammond** [comment]
Having same issue.

**Comment by Is82jM** [comment]
Yeah need update.

**Comment by 1019220756** [comment]
Update the cheat for us!

**Comment by rootm0s** [comment]
Here's the new offsets:
https://gist.github.com/rootm0s/d84651e09a68b9074e86f58e21755361

**Comment by YourFutureBoyfriend** [comment]
Hopefully gets updated with in the week

**Comment by Jire** [comment]
Try [1.0.4](https://github.com/Jire/Charlatano/releases/tag/1.0.4), should be updated now.

**Comment by YourFutureBoyfriend** [comment]
Thank you so much!
