### ISSUE TITLE
Updated signatures. The hack is now outdated.

### ISSUE THREAD

**Issue by Is82jM** [Jire/Charlatano#219]
I confirm that Charlatano is outdated but not VAC detected because of new signatures after new 42mb update or smth. @Jire Will you update the cheat? :)

**Comment by Balouchis** [comment]
Dont make Stupid issues JIRE will update just like he did before! you need to wait!

**Comment by anurag01021996** [comment]
yes confirmed ..not working anymore..
dont worry @Jire will update it soon

**Comment by Jire** [comment]
Try [1.0.4](https://github.com/Jire/Charlatano/releases/tag/1.0.4), should be updated now.
