### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by CodingAlien** [Jire/Charlatano#222]
I ran the build and got an error stating
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

**Comment by Jire** [comment]
Did you extract the contents out of the ZIP? It can get a little confusing telling apart being within a ZIP archive and a regular folder, but the way you can tell is by by the purpleish border. Make sure to extract the folder out of the ZIP first, keeping the contents of the directory intact.

If that doesn't work, try opening a command prompt and navigating to the directory, then launching the script through the prompt.

**Comment by CodingAlien** [comment]
The build finished and left files called kotlin, kotlin-build and kotlin classes?
Ill try opening the file via cmd  but how would that make a difference

**Comment by Jire** [comment]
Are you following the read-me instructions?

**Comment by bero17** [comment]
i extracted the zip , then tried to open "build" and i got the same error , 
i tried with CMD by heading to the directory then opening build and i still got the same error

**Comment by bero17** [comment]
i have JAVA 8 u 121 "not Development kit"

**Comment by Jire** [comment]
@bero17 You need the [Java Development Kit](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) installed in order to build Java software. :smile_cat:

**Comment by bero17** [comment]
Thanks i just read the readme , downloading

**Comment by CodingAlien** [comment]
Charlatano 1.03 worked :/

**Comment by CodingAlien** [comment]
Oh it worked I installed Java SE dev kit again and it worked
strange because I already had it installed and the previous version worked
Any ways thanks as always Jire you absolute legend

**Comment by bero17** [comment]
Worked with Java Development Kit , Thanks
