### ISSUE TITLE
VAC auth error

### ISSUE THREAD

**Issue by Roulettinho** [Jire/Charlatano#23]
Hello, first of all the cheat works great, very nice work.

However, it may be from the cheat or my end but everytime I play with the cheat I get a VAC authentication error. When I play without the cheat I usually fine for 3-4 matches so I starting to believe it may be the cheat since with the cheat I don't last 2 matches without getting kicked because of this issue.

Anyway, just wondering if more people are getting this or it's just me

Thanks

**Comment by jonesdj1** [comment]
in b4 vac wave soon

**Comment by Krouzu** [comment]
I get no problem what so ever? Are you using a different cheat or something?

**Comment by Roulettinho** [comment]
No, using only Charlatano.

It happened again also. I was playing only legit on my main for several days then I decided to use the cheat and it happened in the second match in a row

**Comment by jonesdj1** [comment]
Could be your computer sometimes even when your legit it happens
