### ISSUE TITLE
Error: Could not find or load main class com.charlatano.Charlatano

### ISSUE THREAD

**Issue by sumgui316** [Jire/Charlatano#24]
Hi!

I get this error when I launch it.
Error: Could not find or load main class com.charlatano.Charlatano

It's weird cause it worked perfeclty fine while I was testing it on bots. But once I tweaked the values of Aim.kts I started having this issue.

I tried updating Java an deleting it / redownloading the release and it doesn't work.

**Comment by Krouzu** [comment]
Try re downloading the cheat?

**Comment by sumgui316** [comment]
I did :/

**Comment by sumgui316** [comment]
up?
