### ISSUE TITLE
Is it detected with the new update?

### ISSUE THREAD

**Issue by fappercakes** [Jire/Charlatano#26]

**Comment by Krouzu** [comment]
No undetected as of 2/15/17

**Comment by SquareHeadd** [comment]
Theres another update however. İt's something about AI Detecting cheats. (Sounds intriguing) So Beware
https://www.rockpapershotgun.com/2017/02/16/counter-strike-global-offensive-bots/

**Comment by Krouzu** [comment]
Yeah, but this aimbot makes a random pattern to aim so, this bypasses so far.
