### ISSUE TITLE
Vac Authentication Error

### ISSUE THREAD

**Issue by GlaZex** [Jire/Charlatano#270]
Hello! @Jire  
It seems that recently my friend and I, who of which both use charlatano, are getting vac authentication errors more and more often. I haven't downloaded  anything new recently, and am wondering if this may have something to do with the cheat? I would greatly appreciate any input on how to fix this, since I cannot play competitive without this popping up and abandoning me. I have tried to do everything valve recommends to fix this, but it still reappears. 

If this has nothing to do with the cheat for sure, maybe advice that Valve doesn't give would be very helpful. Thanks in advance!

**Comment by vovashahov** [comment]
close monitoring system by ccleaner. and ur problem will be resolve.

**Comment by GlaZex** [comment]
I don't use ccleaner.
