### ISSUE TITLE
Help Jire

### ISSUE THREAD

**Issue by ChtThX** [Jire/Charlatano#272]
Hello, @Jire! I made some minor improvements for the player, so that the player can change some commands without leaving the game, through keys. Increase / decrease ping-fov-aim max-aim min, enable / disable c4 timer, esp, aim, trigger, skeleton, box, reduced flash, recoil, ... how can I make it available? Another thing, can you help me put this all to be shown on the screen in addition to being shown in the prompt? I was thinking of jlabel, jwindow, ... can you help me, please? Thank you! flavioa.alves@terra.com.br

**Comment by Austin72** [comment]
Pull request.

**Comment by ChtThX** [comment]
Austin72 Do you know how we can print both on the screen and on the console?

**Comment by Jire** [comment]
Make a fork of the project using the Fork button, then clone your fork repository. You can then work directly on your fork repository, and send a pull request to my repository when you think it's ready.

As far as printing to console, `println` will do that for you. Lookup `System.setOut` to print to both console (default `System.out`) and to the "screen" (can do this through LibGDX text show, but you'll have to do all this stuff yourself. There is no "LibGDX console").

**Comment by ChtThX** [comment]
@Jire Ok! Thanks!!!

**Comment by MoofMonkey** [comment]
Close please, issue solved.
