### ISSUE TITLE
Cheat won't start !

### ISSUE THREAD

**Issue by M4jx** [Jire/Charlatano#28]
I get this error when I start the cheat v 0.9.5

Error: Could not find or load main class com.charlatano.Charlatano
Press any key to continue . . .

**Comment by sumgui316** [comment]
same

**Comment by Jire** [comment]
Make sure to keep the folder intact, and within a directory that does not trigger UAC. Also, do not run as administrator, if you were doing so.

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/0.9.7
