### ISSUE TITLE
Better config aim ?

### ISSUE THREAD

**Issue by krypt0n1te** [Jire/Charlatano#280]
Can you tell what is better config to aim to seems legit ?

**Comment by rootm0s** [comment]
Aim assist looks most legit imo. But if you are shit at aiming it won't help much!

**Comment by GlaZex** [comment]
Go to the workshop map Aimbotz and take the time to test what settings work for you. It might take some time, but you get to learn what the possible options are, and its better than being blatant for overwatch.

**Comment by UnknownPerson69** [comment]
You should turn down the FOV and use -insecure in your launch options jic. Then you can try to find your perfect settings in aim_botz (download on steam community maps). Good luck!
