### ISSUE TITLE
Aim

### ISSUE THREAD

**Issue by AutisticFurry** [Jire/Charlatano#285]
Hey I was wondering if anyone is having issue with the aim assist. It just stops working entirely with no errors but everything else works fine. I'm using latest version of 1.0.5-hotfix and my build can be found [here](https://mega.nz/#!NtgHnZBD!LynMEIM5A-ZSYMlOWYg0H91WokVDEodawNiTmWtOuSU). If anyone is having the same issue just say and if anyone knows what is going wrong please help me to fix it.

-Cheers

**Comment by CodingAlien** [comment]
Aim works fine for me

**Comment by ikrypt0** [comment]
aim assist is only supposed to give you small pushes towards the enemy, it shouldn't work like the other aimbots and snap onto the head, it's working, you just don't notice.

**Comment by AutisticFurry** [comment]
@ikrypt0 I know I've been using this for ages and know what everything does. I was having issues where I could tell it wasn't working. I'd aim on then hold left mouse or my aim key and nothing would happen. Was like this for a good 3 or 4 days but for some reason it now working fine.

**Comment by rootm0s** [comment]
@AutisticFurry close this issue then! glad it worked out in the end.

**Comment by AutisticFurry** [comment]
@rootm0s I'll keep it open for another day or so in case the issue comes back again. After that I'll close it.

**Comment by rootm0s** [comment]
@AutisticFurry alright! sounds good.

**Comment by MoofMonkey** [comment]
Juat close this and reopen if bug will appear again. If it does for other members - they can just open new issue and reference thia issue.
