### ISSUE TITLE
Wont work on faceit

### ISSUE THREAD

**Issue by colyM** [Jire/Charlatano#29]
How to bypass that shitty faceit anti cheat client? The cheat wont work if I open with faceit ac ,please help ,ty

**Comment by anass98h** [comment]
i have the same problem plz help

**Comment by Jire** [comment]
Although Charlatano bypasses FaceIT's server-sided anti-cheat, it does not bypass their driver that protects the game process from being accessed by regular user-mode processes-- thus Charlatano cannot work while using the FaceIT client.

**Comment by jdubz93** [comment]
https://douggemhax.wordpress.com/2015/05/27/obregistercallbacks-and-countermeasures/

maybe this will help u bypass it jire
