### ISSUE TITLE
1.0.5 hotfix Reduced Flash is not actually doing anything + ESP glow not working for me

### ISSUE THREAD

**Issue by andreva96** [Jire/Charlatano#294]
Other types of ESP besides Glow works with waay less performance (Reduces to arround 20 FPS's when without the display it creates is stable at 70 FPS)

**Comment by MoofMonkey** [comment]
There's one way to fix it now - upgrade to Windows 10.

**Comment by andreva96** [comment]
really.. ?

**Comment by MoofMonkey** [comment]
Sorry, but yes. https://github.com/Jire/Charlatano/issues/223#issuecomment-310238565
But this comment says that windows 7 && 10 are supported and 8 is unsupported in 1.0.5 https://github.com/Jire/Charlatano/issues/221#issuecomment-310173530

**Comment by andreva96** [comment]
Yeah i am on w7 and Both box and skeleton are working.. Glow ESP is missing from anything tho.
What about Reduced Flash ?

**Comment by MoofMonkey** [comment]
I don't know, may be @Jire can give answer?
BTW all works on Windows 10.

**Comment by andreva96** [comment]
No rest for the wicked xD
i managed to get some FPS's back putting on console "engine_no_focus_sleep 0". Better than nothing.
