### ISSUE TITLE
Wont Install? Please help?

### ISSUE THREAD

**Issue by Erictheawesome** [Jire/Charlatano#299]
Mine wont install properly and i have no clue why, it gets to 0% configured and doesnt change for like an hour.

**Comment by MoofMonkey** [comment]
Screenshots please...

**Comment by Erictheawesome** [comment]
I got it to work. For some reason when it says "executing 0%" you need to close and re-open then it does the next part and you need to keep doing this until it says that the program has finished installing.

**Comment by MoofMonkey** [comment]
Lol, personal bug.
