### ISSUE TITLE
Force Aim Key

### ISSUE THREAD

**Issue by Georgeforemangril** [Jire/Charlatano#31]
How do i change the force aim key? i'm trying to bind it to "Q" or "Alt" but it doesn't run the script. I don't have a gaming mouse so this is why i want to change it. I managed to get the force aim key to work with Q but it stopped working

**Comment by Jire** [comment]
It's as simple as changing the value of `FORCE_AIM_KEY`, inside `settings/Aim.kts`.

https://github.com/Jire/Charlatano/blob/master/settings/Aim.kts#L56

You need to change it to a virtual key code, which you can find a list of here: https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx

The key code is the hexadecimal value, beginning with _0x_. For example, _0x51_ is the _Q_ key, and _0x12_ is the _ALT_ key.

Hope that helps :smile:

**Comment by Georgeforemangril** [comment]
Oh thank you very much! 

Awesome program by the way, works perfectly!
