### ISSUE TITLE
safe to use on ESEA?

### ISSUE THREAD

**Issue by bcintron19** [Jire/Charlatano#316]
is this safe to use on esea? and is it being kept up to date?

**Comment by MoofMonkey** [comment]
Oh please fucking read README
https://github.com/Jire/Charlatano/blob/master/README.md#charlatano

**Comment by bcintron19** [comment]
in other words, i want to know if anyone actually used/uses this on esea, i dont want to just trust it saying "you can play on ESEA for weeks or months", cause that would mean i could eventually get banned for it.

**Comment by tamal777** [comment]
Don't use it. You will be nuked for using it.
