### ISSUE TITLE
Cheats Arent Working For Me

### ISSUE THREAD

**Issue by taariqamozilla** [Jire/Charlatano#324]
Windows 7 
Installed JRE8 and JDK8
uninstalled and rebuilt at least 3 times
Installed Ver of Charlatano 1.0.5 and 1.0.6

runs cmd empty (like normal) but nothing happens.
has 2 sets of javaw in taskmanager

**Comment by MoofMonkey** [comment]
Make update to Windows 10. It's so easy that a child can do this.
And there's universal keys for Windows 10 upgrade, if you don't want to pay for upgrade/torrent old veraion.

**Comment by taariqamozilla** [comment]
Yes, i came to this conclusion earlier and found a old windows 10 boot usb that i made. Im now at my 8th hour of "Making sure you're ready to install"  thanks for the response. Will tell you if it fixes it.

**Comment by MoofMonkey** [comment]
Download media creation tool. It downloads new windows 10 build and installs it w/o USB/DVD/CD removal drive

**Comment by taariqamozilla** [comment]
Will do thanks, bcuz this is still making sure I'm ready to install (started at 2pm 5th Aug, it is now 4am 6th Aug)

**Comment by MoofMonkey** [comment]
what's new?

**Comment by taariqamozilla** [comment]
Still havent had the chance to download new win 10 bcuz of network limitations but will be picking up a new wifi later today.

**Comment by taariqamozilla** [comment]
Have downloaded win 10 and cheats now work ty

**Comment by MoofMonkey** [comment]
np 👍
