### ISSUE TITLE
Charlatano won't startup

### ISSUE THREAD

**Issue by SuperTollerTyp** [Jire/Charlatano#33]
http://imgur.com/a/WM6m3

**Comment by keepo1337** [comment]
Hey @SuperTollerTyp, did you run 'Start Charlatano' as an admin? This might be the problem.

**Comment by SuperTollerTyp** [comment]
Serveral times. Redownloaded a few times.

**Comment by keepo1337** [comment]
Well the thing is, to *not* run it as an admin.

**Comment by Jire** [comment]
You should not run as admin, as @keepo1337 said.

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/0.9.7
