### ISSUE TITLE
I am confused.

### ISSUE THREAD

**Issue by Vikingen01** [Jire/Charlatano#330]
Just here to clearify things...

If you play faceit for free without the client, all the features exept antiflash and rcs are UD right?

And if you play the payd version of faceit with the anticheat, aim path is the only undetected feature?

**Comment by emek1337** [comment]
1. yeap, just use path aim.
2. its not working on faceit client

**Comment by Jire** [comment]
Bunnyhop, ESP, RCS, and path aim are all UD

But Charlatano does not have a bypass for handle restrictions that the FaceIT client imposes.

**Comment by MoofMonkey** [comment]
@Jire, by the way RCS doesn't working ._.
