### ISSUE TITLE
hack is not working when i followed all the steps correctly 

### ISSUE THREAD

**Issue by ranapratap679** [Jire/Charlatano#335]
i build a charlatano hack and i installed lateset jdk and i turned on my game and turned that hack on but when i open cmd it shows it is working but i cant see those hacks in game are not working

**Comment by Glowings** [comment]
1) Try running as administrator. ( Charlatano and CSGO )
2) Delete build folder and try running build.bat again.
3) Make sure your settings within ../Charlatano/build/Charlatano/settings/ are all correct and within Scripts.kts you have enabled the features you want to use.

and again, as i'm sure everyone knows, start it once in game warm-up with a weapon in hand.

**Comment by ranapratap679** [comment]
i dont know about settings in scripts.kys i just needed glow esp

**Comment by MoofMonkey** [comment]
Cheat are only working @ Windows10. Sorry.

**Comment by ranapratap679** [comment]
ohh then if i install windows 10 will it work ?

**Comment by vovashahov** [comment]
yes.

**Comment by ranapratap679** [comment]
but my friend have windows 7 64 bit he can use hacks why is that ?
