### ISSUE TITLE
bombtimer not appearing?

### ISSUE THREAD

**Issue by sheddup** [Jire/Charlatano#34]
I have `ENABLE_BOMB_TIMER = true` in my scripts.kts
![CS:GO Window](https://cloud.githubusercontent.com/assets/5480335/23296394/7fb2e832-fac0-11e6-9720-1b95bd2cc416.png)  
All you can see is the skeleton esp

0.9.6, Win7 x64, jdk 121

**Comment by sheddup** [comment]
Does anyone have a screenshot of the bombtimer actually working, I'm messing about with BombTimer.kt and can't even get bomb.timeLeft() to display in console.

**Comment by fettyrepz** [comment]
How did you get the open gl esp to work? when i run in fullscreen windowed, the screen goes black and shows the esp only no cs go game

**Comment by koassount** [comment]
No, the bomb timer isn't working yet.
