### ISSUE TITLE
New update broke aim

### ISSUE THREAD

**Issue by MoofMonkey** [Jire/Charlatano#344]
New update broke aim

**Comment by charalatnomeister** [comment]
only aim?

**Comment by charalatnomeister** [comment]
i am afriad about ban sure??

**Comment by MoofMonkey** [comment]
Lol, nice bug.
![image](https://user-images.githubusercontent.com/11695747/29441362-795d958a-83d3-11e7-9a68-a630ba966a02.png)

**Comment by tamal777** [comment]
+MoofMonkey can we play together csgo?

**Comment by 4sad** [comment]
offset updated
