### ISSUE TITLE
The New Offsets... 

### ISSUE THREAD

**Issue by SquareHeadd** [Jire/Charlatano#346]
[Offsets]
m_dwClientState = 0x5A4334
m_dwEntityList = 0x4A86B0C
m_dwGlowObject = 0x4FA3288
m_dwForceJump = 0x4F1D988
m_dwForceAttack = 0x2EC8E98
m_dwPlayerResource = 0x2EC721C
m_dwGlobalVars = 0xA65108
m_dwBoneMatrix = 0x2698
m_vecOrigin = 0x134
m_vecViewOffset = 0x104
m_dwLocalPlayer = 0xAA9BBC
m_dwViewAngles = 0x4D10
m_nDeltaTick = 0x174
m_nTickBase = 0x3404
m_hActiveWeapon = 0x2EE8
m_iCrossHairID = 0xB294
m_dwIndex = 0x64
m_iHealth = 0xFC
m_iTeamNum = 0xF0
m_iClip1 = 0x3204
m_iShotsFired = 0xA2A0
m_bDormant = 0xE9
m_fFlags = 0x100
m_bSpottedByMask = 0x97C
m_dwInGame = 0x108
m_lifeState = 0x25B
m_angEyeAngles = 0xB22C
m_iPlayerC4 = 0x161C
m_bIsDefusing = 0x3884
m_flNextPrimaryAttack = 0x31D8
m_nFallbackPaintKit = 0x3170
m_iItemDefinitionIndex = 0x2F88
m_iItemIDLow = 0x2FA4
m_iAccountID = 0x2FA8
m_OriginalOwnerXuidLow = 0x3168
m_vecVelocity = 0x110
m_aimPunchAngle = 0x301C
m_iWorldModelIndex = 0x31E4
m_nModelIndex = 0x254
m_hViewModel = 0x32DC
m_hMyWeapons = 0x2DE8

**Comment by inacumb** [comment]
And where do I put those in the source?

**Comment by Anteja3** [comment]
i have no idea where to put those. build.bat not working so it can't even build the cheat x.X

**Comment by 4sad** [comment]
here!
https://github.com/Jire/Charlatano/tree/master/src/main/kotlin/com/charlatano/game/offsets

**Comment by Jmayy** [comment]
4sad I went there but where do i place them all the files does not contain that offset format. .-.

**Comment by darknayt** [comment]
They have another format but i can't find many offset is it normal ?

**Comment by wuwujia** [comment]
@Jire please teach us how to update manually

**Comment by nooleke18** [comment]
Can anyone upload done, zip or .rar ?
Because dont know how edit offsets.

**Comment by kominxe** [comment]
ehh m8, u paste a new offsets, but Jire using a pattern scanner.
all pattern are good but in new update valve change a weapon system structure.
we must wait for @Jire

**Comment by koassount** [comment]
haha, you fags are hella retarded

**Comment by aqsatti** [comment]
Can someone tell me where to place the offsets like in clientoffsets.kt or what?
