### ISSUE TITLE
Aim Assist

### ISSUE THREAD

**Issue by HoopGit** [Jire/Charlatano#35]
How does Aim Assist work? I realise it's supposed to correct ur aim slightly, but is this automatic or does it happen when I press the aim key? I turned off the Enable on fire feature of the aim script, and am now a little lost because it seems that unless I press the aim key, nothing happens. But I'm wondering if pressing the aim key makes the normal aimbot turn on or the aim assist.
Cheers

**Comment by Jire** [comment]
If you turn off the enable on fire feature, the aim assistance will only activate when holding the aim key (button 5, usually on the bottom of the left side of your mouse).

Enabling aim assist mode overrides the default aimbot, and thus the controls are the same.
