### ISSUE TITLE
Jire trolling us !! XD :P

### ISSUE THREAD

**Issue by ShaifAslam** [Jire/Charlatano#353]

**Comment by SolaKun** [comment]
LOL

**Comment by Jire** [comment]
Well those two commits fix aim and RCS, just in a meme way

**Comment by tamal777** [comment]
what do you mean?

**Comment by SquareHeadd** [comment]
lol. nice memes @Jire ...
Like are we gonna get offset memes as well ?... :)))

**Comment by wuwujia** [comment]
Excuse for my poor understanding ,what's "just in a meme way" said by Jire?

**Comment by Glowings** [comment]
Or he's just updating it in his own time?? QQ
its a free open-source cheat, we cant expect it to be updated on the dot.

**Comment by Jire** [comment]
It's already updated lul

**Comment by Anteja3** [comment]
i click on build.bat and it says "gradlew is not recognized as an internal or external command, ..... bla bla bla" Q~Q what to do???

**Comment by SquareHeadd** [comment]
@Jire  uhm wut ?

**Comment by 4103chan** [comment]
It is. You just have to try and build it. It works fine now

**Comment by ShaifAslam** [comment]
lol ..I was just joking guys ...its working as before...if u still face any error or problem try to debug it ...It took me a day to understand the whole working of the code now i am able to modify it as desired ....@jire let them figure out themselves its a good way to influence kotlin :P....I am java developer after  working on this project ..I am in love with kotlin its so easy XD

**Comment by SquareHeadd** [comment]
so I just have to re built it ?

**Comment by SquareHeadd** [comment]
my aimbot is still not working. Idk what to do ?. Can somebody help pls ?...

**Comment by anurag01021996** [comment]
Yeah...I have successfully built ...but rcs doesn't seems to work for me..although aimbot working perfectly :)..
Help me if anyone got it working ...

**Comment by sunke5616** [comment]
Yeah...I have successfully built ...but aimbot doesn't seems to work for me..although rcs working perfectly :)..
Help me if anyone got it working ...

**Comment by SquareHeadd** [comment]
wtf ::::::D 
lets just help each other out. ...

**Comment by SolaKun** [comment]
update 
https://github.com/Jire/Charlatano/blob/master/src/main/kotlin/com/charlatano/game/netvars/NetVarOffsets.kt#L54
to
```
val iWeaponID by netVar("DT_BaseCombatWeapon", "m_iItemDefinitionIndex")
```
fix the Aim and RCS for me
