### ISSUE TITLE
Cheat not injecting

### ISSUE THREAD

**Issue by Swag1337** [Jire/Charlatano#36]
http://prnt.sc/ed2s6q

how to fix this?

**Comment by keepo1337** [comment]
@Swag1337 I have the same problem. My cmd is showing up the exact same message. But actually, you can ignore this warning. You may have to wait up to a minute (I would suggest to try it in a botgame in something like a trainingmap) to let it start ingame. If it doesn't work, try to make an exception in your firewall or even disable it for the time you use Charlatano. You also don't need to run it as an admin. If this didn't help, feel free to ask.

**Comment by Georgeforemangril** [comment]
@Swag1337 Do you have the most recent release? Have you updated JAVA? Did you run it when not in game with a weapon in hand? I find it's best to run the cheat when you're in warmup or start it in a offline game. If you start it in offline game, wait for it to come up, test it out etc, then go into a comp game or any game you want

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/0.9.7
