### ISSUE TITLE
is this detected?

### ISSUE THREAD

**Issue by NekoRem** [Jire/Charlatano#372]
ive used this cheat on my old vac account on insucure servers but i don't want to ban my current account

**Comment by 4sad** [comment]
no

**Comment by NekoRem** [comment]
so i wont get vac ban?

**Comment by MoofMonkey** [comment]
...................................
WON'T DETECTED.

**Comment by NekoRem** [comment]
wont detected, doesn't make sense???

**Comment by tamal777** [comment]
It is not detected.

**Comment by MoofMonkey** [comment]
not detected == no VAC
otherwise you can get OWd

**Comment by NekoRem** [comment]
k thanks

**Comment by MoofMonkey** [comment]
Edit: changed otherwise to but.
Sorry for bad eng ;D
