### ISSUE TITLE
Whenever I try to build it I get this error: [SOLVED]

### ISSUE THREAD

**Issue by EpicBoi** [Jire/Charlatano#377]
e: Compiler terminated with internal error
:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.056 secs
Press any key to continue . . .

**Comment by Nvthvnz** [comment]
You dont have java

**Comment by EpicBoi** [comment]
I do
