### ISSUE TITLE
How to complete uninstall this hack?

### ISSUE THREAD

**Issue by Roulettinho** [Jire/Charlatano#38]
I see that the hack downloads a lot of kotlin stuff, is there a way to uninstall altogether?

**Comment by koassount** [comment]
Why would you even care to uninstall it? you can't "uninstall" it anyways, you can just delete the files.
Kotlin has nothing to do with the cheat per se.

**Comment by Jire** [comment]
Besides the folder / archive, Charlatano uses Capsule's Maven Capsule feature to download libraries which are places in `%appdata%\capsule`
