### ISSUE TITLE
Build to DLL?

### ISSUE THREAD

**Issue by viniciuspwd** [Jire/Charlatano#401]
Is there a way to build Charlatano to a dll file, turning it to an internal cheat?

Thank you @Jire, you're awesome!

**Comment by w-o-a-h** [comment]
what no wtf are you on this is made in java

**Comment by Jire** [comment]
If anyone has to ask, they probably don't have the technical ability to make it happen.

So in short, no, and in practicality this idea is contrary to the benefits of the project.

**Comment by viniciuspwd** [comment]
Thanks Jire!
