### ISSUE TITLE
Aimbot question

### ISSUE THREAD

**Issue by attitude12** [Jire/Charlatano#404]
I'v been using the cheat for a while, testing on a dummy account and everything works fine, except path aim which is not working whatsoever.
But i got a question/issue..
I play with very low fow and fast playback speed on the aimbot.
Sometimes when an enemy is shoulder peeking if i shoot him and he goes back behind the wall, if i press left click to shoot( and activate the aimbot) my crosshair goes with him so i end up shooting at the wall.
Not only that it's obvious but it's also annoying. Is there anyway to make the aimbot stop working if the enemy is behind a wall or anything else?

**Comment by Jire** [comment]
Besides implementing a faster check yourself, no. Typically to prevent this I don't use left click aim, instead I let go when they go near the wall.

**Comment by attitude12** [comment]
Got it, thanks for the answer.
