### ISSUE TITLE
HACK STOPPED, BUILD FAILED SAYING COMPILOR ERROR

### ISSUE THREAD

**Issue by kishanml299** [Jire/Charlatano#408]
![csgo](https://user-images.githubusercontent.com/29768678/30438965-3497c970-9990-11e7-9f9c-079c6100a6c9.png)

i used to use the hack it was working well . but from today hack stoped working and i tried to build again but it wouldnt take it giving the error in the link help ME OUT PLS

**Comment by tamal777** [comment]
reinstall java

**Comment by kishanml299** [comment]
no i did . doesnt work @tamal777

**Comment by viniciuspwd** [comment]
Are you sure you installed JDK, not the JRE?

JDK link: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by kishanml299** [comment]
YES SIR! its JDK i m sure of it . yes from the same link @viniciuspwd

**Comment by kishanml299** [comment]
ok uninstall the JDK clear temporary files and reinstall JDK it works thank you guys : )
