### ISSUE TITLE
gg detected

### ISSUE THREAD

**Issue by denizdeni** [Jire/Charlatano#411]
DON'T USE IT HACK IS DETECTED

**Comment by w-o-a-h** [comment]
proof

**Comment by mayankbisht9797** [comment]
can someone confirm? with steam id link?

**Comment by attitude12** [comment]
Can anyone confirm this?

**Comment by Nackenschelle** [comment]
got also banned but more than just csgo most of the valve games

**Comment by koassount** [comment]
U guys r all mentally ill lmao

**Comment by attitude12** [comment]
I don't know what to believe, i read that and i played with a smurf account, 3 hours passed, still not vac'ed.

**Comment by kishanml299** [comment]
wtf dude . nope not detected . i m still using it ❌ . @Jire any response from u my god?

**Comment by ChtThX** [comment]
no vac!!!

**Comment by tamal777** [comment]
shit sliver noob this is for only cs go you can't get vac ban on other valve games by using this only on csgo. fake news.

**Comment by gwbrielhcg** [comment]
I USE HYPESENSE
