### ISSUE TITLE
@Jire !! charlatano couldnot break the record of abendigo :P RIP all

### ISSUE THREAD

**Issue by ShaifAslam** [Jire/Charlatano#412]
Advice!! dont use use public cheats in VAC secured servers...if it gets enough attention they will signature it and ban you.

**Comment by attitude12** [comment]
Do you have proof it's detected?

**Comment by Nackenschelle** [comment]
VAC Ban comes with a delay
maybe tomorrow or next week
i used it for one round last week and got banned yesterday

**Comment by attitude12** [comment]
That's bull. I've been using it every day for over 2 weeks. I even had some "not-so-legit" matches where i got mad and went full retard mode(on a smurf account ofc). It's either other hacks you guys have been using or it's an overwatch ban. Vac doesn't detect Charlatano yet.
