### ISSUE TITLE
Change color when the enemy is visible

### ISSUE THREAD

**Issue by ChtThX** [Jire/Charlatano#414]
@Jire @Jonatino @lzienius @ryleykimmel 
How can we do that? I was looking at the code, but I did not see a solution. can you help me?

**Comment by ShaifAslam** [comment]
u can see it in aimtux source code and code it in kotlin here

**Comment by Austin72** [comment]
Ill do this for you I guess,
So you're going to need to edit https://github.com/Jire/Charlatano/blob/master/src/main/kotlin/com/charlatano/scripts/esp/GlowESP.kt

At line 44 change:
`				if (SHOW_ENEMIES && !team) {
					glowAddress.glow(ENEMY_COLOR)
					entity.chams(ENEMY_COLOR)
				}`

to something like:
`				if (SHOW_ENEMIES && !team) {
						if (entity.spotted()) {
							glowAddress.glow(ENEMY_COLOR)
							entity.chams(ENEMY_COLOR)
						} else {
							glowAddress.glow(ENEMY_COLOR2)
							entity.chams(ENEMY_COLOR2)
						}
				}`

Be sure to define ENEMY_COLOR2 or add it to the settings or whatever.

**Comment by koassount** [comment]
> u can see it in aimtux source code and code it in kotlin here

LMAO LOL KYS HAHA

**Comment by MoofMonkey** [comment]
Wow, @Jonatino appearing

**Comment by ChtThX** [comment]
Hey, thank you.

I could not do it. Please, can you help me? Which files do I need to move?
What do I need to change? If you can, tell me in detail. by myself, I could
not do it. Sorry and thank you.

2017-09-15 14:44 GMT-03:00 Austin72 <notifications@github.com>:
