### ISSUE TITLE
Is this detected or undetected?

### ISSUE THREAD

**Issue by haxin1337** [Jire/Charlatano#416]
With the new update I've seen people say it is and isn't... which is it?

**Comment by FmanZ** [comment]
Well I've been using this for some weeks now, not detected (for me at least?)

**Comment by haxin1337** [comment]
after the most recent update? Have you played in past like 10 hours with it?

**Comment by attitude12** [comment]
It's not detected. Been using it all day, on two different accounts. It's safe to use, at least now.

**Comment by haxin1337** [comment]
thanks mate
