### ISSUE TITLE
Cant build 1.0.6 early

### ISSUE THREAD

**Issue by theone9032** [Jire/Charlatano#418]
I try to double check i have correct jdk installed and when i click on build bat i get this error:  Compiler terminated with internal error
:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.892 secs
Press any key to continue . . .

Can someone help me please?

**Comment by MoofMonkey** [comment]
Download pre-built cheat from github.com/Austin72/Charlatano/releases

**Comment by MoofMonkey** [comment]
Download pre-built cheat from github.com/Austin72/Charlatano/releases

**Comment by theone9032** [comment]
@MoofMonkey Now im getting a different error...

Only continue once you are in game and can see your gun.
'java' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

**Comment by MoofMonkey** [comment]
Install java (facepalm)
java.com

**Comment by theone9032** [comment]
@MoofMonkey Well that wasnt the problem lol, im a java programmer of course i have java installed (i also checked three different times today i had the correct version installed) the problem was that i did not have my JAVA_HOME path set. i figured it out and it seems to be working now. ill close this discussion
