### ISSUE TITLE
how to turn off ESP

### ISSUE THREAD

**Issue by creepz270x** [Jire/Charlatano#420]
guys can someone help me, how to turn off ESP or Toggles in Charlatano ?
iam try to false something related with ESP but it doesnt work.

thx

**Comment by MoofMonkey** [comment]
build/Charlatano ***/settings/Settings.kts
ENABLE_ESP = false

**Comment by Austin72** [comment]
in "settings\scripts.kts"
ENABLE_ESP = false

**Comment by sunke5616** [comment]
my ESP don't work... u can ?

**Comment by creepz270x** [comment]
still not working

**Comment by MoofMonkey** [comment]
> how to turn off ESP or Toggles in Charlatano
 > still not working
wtf?..

**Comment by dellem1** [comment]
stupid question
