### ISSUE TITLE
Aim settings/Aim assist?

### ISSUE THREAD

**Issue by globalelite2** [Jire/Charlatano#43]
Hi, how does aim assist work? And how to enable it, to make it look more legit as possible? Is it possible disabling aim lock, but enabling aim assist? What's perfect_aim?

**Comment by ShOtzzLIVE** [comment]
You can edit the different settings files by using [https://notepad-plus-plus.org/](Notepad++)
If you need help editing the files, please join the discord.

Perfect aim, is perfect aim...
