### ISSUE TITLE
Console issue

### ISSUE THREAD

**Issue by inZaniTyy** [Jire/Charlatano#44]
Whenever I try to "Start Charlatano 0.9.6-hotfix" console shows me 'Error: Could not find or load main class com.charlatano.Charlatano' then press any key to continue, upon pressing any key the command prompt just shuts down. 

Thanks in advance

**Comment by Jire** [comment]
Keep the folder intact, and do not run as admin.

**Comment by inZaniTyy** [comment]
If by intact you mean not move anything in or out of the extracted folder then I already did both. :/

**Comment by Jire** [comment]
Add me on Skype: Jire..

**Comment by inZaniTyy** [comment]
Done.
