### ISSUE TITLE
It stops aiming when the enemy is in the air. 

### ISSUE THREAD

**Issue by SquareHeadd** [Jire/Charlatano#444]
Is there a way to make aimbot aim when ppl are in the air .
or jire maybe can you do smth about this ?
thank you...

**Comment by Austin72** [comment]
_in Charlatano/src/main/kotlin/com/charlatano/scripts/aim/General.kt_

replace line 125
**} else if (currentTarget.onGround() && me.onGround()) {**

with
**} else {**

**Comment by SquareHeadd** [comment]
Unfortunately didn't work. any idea why ?. or can you send me the kt file maybe ?. 
I would appriciate it, thank you.

**Comment by 4103chan** [comment]
Did you recompile it afterwards...?

**Comment by SquareHeadd** [comment]
Yes but it gave an error ( what should I DO )
![fuck me](https://user-images.githubusercontent.com/25720109/34078159-9af282f8-e325-11e7-8751-0b03b2dad876.jpg)

**Comment by w-o-a-h** [comment]
thats because you did not do it right

**Comment by SquareHeadd** [comment]
@w-o-a-h And how I'm I supposed to do?

**Comment by SquareHeadd** [comment]
Nevermind I think I got it
