### ISSUE TITLE
CHARLANTANO not working please help

### ISSUE THREAD

**Issue by sheyhan** [Jire/Charlatano#446]
so um the machine iam running is win 8.1 and charlantano isnt working but my friend is using windows 8.1 too and hes is working.Can someone help me?

**Comment by creepz270x** [comment]
reset build

**Comment by sheyhan** [comment]
like rebuild the hack? cus i already did that......

**Comment by sheyhan** [comment]
wait does it only work on win 10?

**Comment by sheyhan** [comment]
if so how de hell my friend is running it on 8

**Comment by ikrypt0** [comment]
works with windows 7 and 10

**Comment by Jire** [comment]
If you're using Windows 8 or 8.1 you can't use the OpenGL overlay, so you need to disable box ESP, skeleton ESP, and bomb timer.

**Comment by sheyhan** [comment]
will it work then?

**Comment by sheyhan** [comment]
ok never mind it worked.thanks guys
