### ISSUE TITLE
Cant Edit ESP and when relaunch I get blackscreen

### ISSUE THREAD

**Issue by Time2Own** [Jire/Charlatano#449]
Hi

So basically when I try to edit the settings in game for ESP it does not work for example the 3D ESP Box = true and the ESP glow = false.

After I quit the cheat and relaunch it also gives me a black screen until I press ctl + alt + del and open task manager, which then something fixes the problem but majority of the time its just a black screen.

I really appreciated your open source work done here. Someone also told me that you are allowed to modify the code for your cheat into my own and the sell it? Wanted to know if that's true as well.

Also, Can anyone confirm what platforms this is undetected on apart from Vac?

**Comment by tamal777** [comment]
enable windows aero theme.

**Comment by Time2Own** [comment]
Please remove all of my posts.
