### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ljanemi** [Jire/Charlatano#45]
![](http://image.prntscr.com/image/60a1bb86f0b34fb6b4b79e5ff497d45b.png)

**Comment by Jire** [comment]
To build any Java app you need the JDK: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by ljanemi** [comment]
I have it, and it's the latest update

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/0.9.7
