### ISSUE TITLE
FALSE Warning VAC BAN'd

### ISSUE THREAD

**Issue by Time2Own** [Jire/Charlatano#452]
I just got VAC Banned for the first time of cheating in 2 years. on both accounts even after deleting this cheat. You did excellent job Jire but sorry for the bad news. I love and respect how you make things open source but this was bound to happen.

**Comment by Time2Own** [comment]
http://steamcommunity.com/id/HelloIamJohnFromChinaHello/

**Comment by ChtThX** [comment]
I'm playing all day and I did not take ban.

**Comment by Time2Own** [comment]
CHEATS USED: LEAGUECHEATS, LEAGUEMODE, PLATINUMCHEATS AND Charlatano

**Comment by Time2Own** [comment]
I only used Charlatano yesterday. I had nothing else on my PC neither of the cheat above mentioned. Next day VAC

**Comment by AutisticFurry** [comment]
Possible delayed VAC from the others

**Comment by Time2Own** [comment]
Sorry you guys are still undetected. I have come to realize that Leaguecheats was hit with a VAC wave and I was banned even though I used the cheat over 2 weeks ago. Im aware that VAC bans can take be delayed upto 6 months. Sorry Jire for false warning. #Closed
