### ISSUE TITLE
Java compatibility

### ISSUE THREAD

**Issue by AK2H** [Jire/Charlatano#456]
I am getting this error when I run the build on Java 9.0.1 :

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Press any key to continue . . .

**Comment by AK2H** [comment]
What is the last compatible version ?

**Comment by COLATHOS** [comment]
Hi Akl2h. Sorry, I do not know the answer of your question ... I do not know if the friend Jire is still active. Anyway, do you use Charlatano frequently ? The hack seems safe. I played many hours with. No VAC BAN. But the ESP is not working any longer. And the triggerbot should be upgraded. What do you think about the aim (perfect aim, asssist aim) ? Should be upgraded also. Don't you think ?

**Comment by AK2H** [comment]
Yes I have been using it for the last 4 months.
ESP is working fine for me.
The aim is good, but can't really judge because I have relatively high ping (100~130) which can affect the results. However when I play offline it's like god mode!

**Comment by FocuzJS** [comment]
Doesn't build on Java 9x yet even though build instructions say 8 or later; just search "jdk8" and "java install" to get JDK and JRE 8

**Comment by COLATHOS** [comment]
@AK2H : your ESP is working fine ??? Do you use Glow, skeleton or box ? Neither are working right now. I have no ESP at all. Do you confirm that ?? For other players, is ESP working too ??

**Comment by COLATHOS** [comment]
Before building the "build folder", do i have to select the good settings first ?? (ESP true, trigger true, etc) or do I have to change the settings in the folder "build" ? I do not understand why ESP not working ....

**Comment by COLATHOS** [comment]
Hmmmmmm...... I use Windows 7. Do you think Windows 7 could be an issue for Charlatano ?

**Comment by attitude12** [comment]
At the moment, Charlatno works only on Windows 10.

**Comment by FocuzJS** [comment]
Windows 10 latest update, use glow ESP if the opengl layer is broken for you too
