### ISSUE TITLE
LEGIT JUST GOT VAC AUTHENTICATION ERROR!

### ISSUE THREAD

**Issue by NekoRem** [Jire/Charlatano#460]

**Comment by NekoRem** [comment]
i wasnt using anythig else, im playing mirage rn and got an error NOT BAN!

**Comment by tamal777** [comment]
share your profile link.

**Comment by NekoRem** [comment]
http://steamcommunity.com/profiles/76561198355487169/

**Comment by tamal777** [comment]
nothing to worry about it is not detected. Vac was drunk. https://www.reddit.com/r/GlobalOffensive/comments/396ys1/vac_authentication_error_what_it_is_why_it/

**Comment by AutisticFurry** [comment]
You just need to restart and if the error is still there just verify cashe

**Comment by 4103chan** [comment]
I get VAC auth legit like every week.

Dont piss yourself and close the issue.
