### ISSUE TITLE
How do I get aim to work 1.0.5?

### ISSUE THREAD

**Issue by onowasd** [Jire/Charlatano#462]
I can get pretty much everything to work but aim and RCS, ive rebuilt, uninstalled and uninstalled JDK and it doesn't make a difference. I have windows 10 can anyone fix this issue?

**Comment by Jmayy** [comment]
Get 1.0.6 aim doesn't work anymore in 1.0.5

**Comment by onowasd** [comment]
only bhop seems to work for me in 1.0.6 :/

**Comment by COLATHOS** [comment]
@onowasd same for me. Does not work for 1.0.6 for me too .... May be some updates are "too new" for Charlatano. Could someone (with Charlatano working perfectly) try to use latest updates (JDK, W10, etc) in order to compare ? Thanks
