### ISSUE TITLE
1.0.6 Build Failed

### ISSUE THREAD

**Issue by StickyPenis** [Jire/Charlatano#467]
e: Compiler terminated with internal error
:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.931 secs
Press any key to continue . . .

**Comment by rootm0s** [comment]
I had to reinstall my JDK, then it worked! :)

**Comment by infam0us29** [comment]
You have to make sure you are running the jdk 8u152 version if you have the lasted Java installed. Also I had an issue using the jdk 9.0.1 version with the build as well so down graded to 8u152
Hope this helps

**Comment by StickyPenis** [comment]
Thanks to you both, it worked! :)
