### ISSUE TITLE
Still doesn't work ..... I spent up to 10 days to fix the issues in W10 

### ISSUE THREAD

**Issue by COLATHOS** [Jire/Charlatano#468]
Thanks Jire for your last release (15)
It was my dream to fix my issues

Grrrrr. Charlatano still does not work :-[ 
I used all the tricks and tips mentionned in the threads.

- My Windows 10 is updated (activated also)
- JDK 8-152 OK
- many compiles
- all the process deeply followed
- Many hours to read and read again all the posts ...

Grrrrr...
I really deserve to use Charlatano :-)))))
I think i am not alone to meet this issues

But I do not give up that easily

**Comment by Jire** [comment]
Possibly some eccentric issue, please leave your Discord contact or Skype

**Comment by StickyPenis** [comment]
I don't know if it works for you, but it did for me. 
I installed JDK 8-151, you can try it too. If that doesn't work, I don't know.

**Comment by tamal777** [comment]
what issue are you facing?

**Comment by COLATHOS** [comment]
That's it, everything works PERFECTLY ! I do not dare to say the stupid reason why the program did not work: I used the version x64 of Jdk-8u151 .... So many time wasted. I should hang myself ! But I am so happy now. @Jire: your program is amazing. I was right not to give up so easily. Thanks a lot for your stunning job and for your help. And for all the threads posted where tips and tricks are spread. Very usefull to take time to read most of them. All answers to fix the clues are written  :-))))))

**Comment by COLATHOS** [comment]
That's it, everything works PERFECTLY ! I do not dare to say the stupid reason why the program did not work: I used the version x64 of Jdk-8u151 .... So many time wasted. I should hang myself ! But I am so happy now. @Jire: your program is amazing. I was right not to give up so easily. Thanks a lot for your stunning job and for your help. And for all the threads posted where tips and tricks are spread. Very usefull to take time to read most of them. All answers to fix the different issues are written :-))))))

**Comment by rootm0s** [comment]
Please close the issues when they are solved 👍
