### ISSUE TITLE
Developer Seeking Help with Charlatano exception

### ISSUE THREAD

**Issue by rozarlive** [Jire/Charlatano#477]
I am mainly a  C# developer with some Java experience. I picked up Kotlin recently and I would like to contribute to this project hopefully within the next 2 months after I get up to speed.  I have a few questions and any help is appreciated.

I imported the project with Intellij IDE and it builds and compiles fine but throws an exception during runtime which is caught by the retry function.  the code is unable to open the csgo process. 

fun openProcess(processID: Int, accessFlags: Int): WindowsProcess {
		val handle = JNAKernel32.OpenProcess(accessFlags, true, processID)
		return WindowsProcess(processID, handle)

 the process ID and accessflags return values, but the handle is null which throws an exception. 

i am using windows 10 64bit, offline csgo version 1.36.1.4

**Comment by Jire** [comment]
Make sure neither Steam nor CS:GO are running as admin

**Comment by rozarlive** [comment]
@Jire  thanks for the help. It wasn't exactly that as but it helped me figure it out. The game wasn't being run as an administrator but I needed to run Intellij IDE as admin.   There is a comment in the code where you briefly talk about processes and modules and that we have to understand them well. Is there a good read/article that you recommend about the subject?
