### ISSUE TITLE
Suggestion: Issue template

### ISSUE THREAD

**Issue by rootm0s** [Jire/Charlatano#478]
Would be great if we could agree and create a issue template which people can use when having problems rather than posting shit issues with no valid/good information.

I suggest that if a issue has been created without the template it should be removed/closed. 

Anyone agree?

**Comment by COLATHOS** [comment]
The use of Charlatano must be deserved. Everything is written for those who are willing to give themselves the time to read the previous messages and to understand the reasons of their problems. Everything is written to fix the issues and well explained by Jire and others. TAKE TIME TO READ PREVIOUS THREADS !!!!!!!!!!!!

**Comment by rootm0s** [comment]
@COLATHOS  you have no clue what im talking about.

**Comment by dan993398** [comment]
@rootm0s ignore that guy he is mentally sick

**Comment by tamal777** [comment]
@dan993398  you are a pussy ass kid. You should learn and understand what he has said. You are using a free, vac free cheat. You guys don't deserve it. @COLATHOS I agree with him. It's a free cheat what are you complaining about @rootm0s you dick? Everything is written on those files and they already have a video how to use it. If you have a issue then real all the topic. Lazy cunts wants some free technical support.

**Comment by rootm0s** [comment]
@tamal777 you're not getting the point.

The point of this thread was: It would be good to have a Issue Template that people can use when creating issues so it would be easier to clean out old/bad/retarded/incompetent issues. Meaning, we get rid of all the "please help me i need free support" issues.

**Comment by bonzobudy** [comment]
issue template on github is useless at preventing shitty issues. retards just ignore the issue template.

**Comment by tamal777** [comment]
@rootm0s It is useless. Idiots will ignore it.

**Comment by dan993398** [comment]
I AM READY TO PAY JIRE IF HE MAKE THIS CHEAT PRIVATE & IMPROVE IT .... NOT LIKE U DICKHEAD

**Comment by rootm0s** [comment]
Die in cancer little turd @dan993398

**Comment by tamal777** [comment]
@dan993398 Jire make cheat programme for fun. If he wants to make money with them he can easily done it. But he wants everyone to use his cheats and enjoy it. You can't buy everything with money. You can donate him tho. Hope you get an overwatch ban soon.

**Comment by dan993398** [comment]
salty peoples

**Comment by dan993398** [comment]
@rootm0s u fuking retard i wanted to help u .. n ur cursing me .. lol

**Comment by bonzobudy** [comment]
rofl u all are such retarded pieces of shit :joy:

should just close issues entirely imo. wanna report a bug? learn how to write a test case and submit it as a pr.
