### ISSUE TITLE
Aimbot snapping

### ISSUE THREAD

**Issue by grangiebb** [Jire/Charlatano#48]
So the aimbot seems to be snapping down and acting all funny even with smooth up high. Anyone ellse had this issue?

**Comment by fin3st** [comment]
hey, 
i had the same issue... i think the FOV is to high ( Standart = FOV 190 )

My Settings:
AIM_FOV = 30
AIM_SPEED_MIN = 1
AIM_SPEED_MAX = 2
AIM_STRICTNESS = 2.0

Aimbot will not snapping down with this settings.

**Comment by grangiebb** [comment]
Thanks mate, I appreciate it.
