### ISSUE TITLE
Build went fine, but won't run?

### ISSUE THREAD

**Issue by Str1de** [Jire/Charlatano#492]
WARN: [kts] kotlin.script.experimental.dependencies.DependenciesResolver.NoDepen
dencies must have a constructor without required parameters

Help?

**Comment by tamal777** [comment]
see the tutorial video how to use it.

**Comment by COLATHOS** [comment]
@Str1de : tamal777 is right. All is written. Read the previous threads (cloed included, until june 2017) and open your eyes ! All issues fixed. 
..... Or leave Charlatano. A lot of hazards could cause VAC BAN for those blindminded . Charlatano must be deserved. Beware of your account ...

**Comment by COLATHOS** [comment]
Jire is a sort of superbrain. Charlatano must be deserved. Only happy-few allowed

**Comment by Str1de** [comment]
I’ve clearly tried all options before posting. Please don’t insult my intelligence. Anyone with real information care to help?
