### ISSUE TITLE
@jire I want to know. When everyone compiles Charlatano, does it make the signature different?

### ISSUE THREAD

**Issue by tamal777** [Jire/Charlatano#523]
I have edited one file Charlatano/blob/master/src/main/kotlin/com/charlatano/game/netvars/NetVarOffsets.kt will it change the signature?

**Comment by tamal777** [comment]
@Jire I want to know please

**Comment by Jire** [comment]
No, Charlatano relies completely on JVM heuristic runtime compilation (like JIT) to provide "safety". There is no real safety implemented, as I'm not interested in releasing a free cheat with safety (and I'm sure nobody else is as well).

**Comment by tamal777** [comment]
okkk thanks bro.
