### ISSUE TITLE
help

### ISSUE THREAD

**Issue by xiaohancf** [Jire/Charlatano#532]
How to turn off Automatic fire ?

**Comment by MuhammadSajid1** [comment]
For this, you need to change the line 'ACTIVATE_FROM_FIRE_KEY = true' in the Aim.kts file to 'ACTIVATE_FROM_FIRE_KEY = false'.

**Comment by xiaohancf** [comment]
Thanks dude. Another question, can i add some junk code or can i compile it based on yours ?
