### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by Polethaw** [Jire/Charlatano#54]
The bunnyhop script doesn't work, it just jumps once and causes the weapon wheel to spazz around, and it won't turn off even if I remove the script from the entire file. The trigger script also won't turn off, and the aim script is really shoddy. Last but not least, the esp only loads enemies about 40% of the time, but loads my entire team completely.

**Comment by fin3st** [comment]
learn to read the readme file -.-

* Enables the bunny hop script.
 *
 * !!! IMPORTANT NOTE !!!
 *
 * You need to unbind the bunnyhop key, and bind mwheelup and mwheeldown to jump.
 * To do this, type the following commands into the in-game developer console:
 * unbind "space"
 * bind "mwheelup" "+jump"
 * bind "mwheeldown" "+jump"
