### ISSUE TITLE
Is there a way to make a hotkey so whenever I press a certain key I can toggle it on/off esp. etc..

### ISSUE THREAD

**Issue by SquareHeadd** [Jire/Charlatano#55]

**Comment by Krouzu** [comment]
Not currently.

**Comment by sheddup** [comment]
I created a toggle where you type 'esp' in the console to toggle on/off but I couldn't get a keybind to work, if anyone knows how to get org.jire.arrowhead.keyReleased to work and only fire once I should be able to create a toggle key.

**Comment by koassount** [comment]
used to work like http://pastebin.com/yrtPUrPL in abendigo  maybe you can come up with smth

**Comment by sheddup** [comment]
Do you have the full code for that abendigo version?

**Comment by sheddup** [comment]
I made a quick toggle only for enemy esp, if someone wants a toggle for the entire esp then thats a little more complicated(for me at least) I'm not going to make a pull request unless Jire wants it.
Default toggle key is F9, you can change the TOGGLE_KEY variable in settings/ToggleESP.kts just like you would with the bunnyhop key
[Charlatano-ToggleESP(a71d729).zip](https://github.com/Jire/Charlatano/files/836601/Charlatano-ToggleESP.a71d729.zip)
Source is there, files I created/modified are
`
com/charlatano.kt
com/scripts/ToggleESP.kt
com/charlatano/settings/ToggleESP.kt
/settings/ToggleESP.kts
`

**Comment by SquareHeadd** [comment]
After tons of downloading it failed.
![cats](https://cloud.githubusercontent.com/assets/25720109/23861834/ef5bd648-0813-11e7-9508-376cb32b43cd.jpg)

**Comment by sheddup** [comment]
Were you able to build Charlatano before? here I built it for you tell me if it works.
[Charlatano-ToggleESP(a71d729).zip](https://github.com/Jire/Charlatano/files/838886/Charlatano-ToggleESP.a71d729.zip)

**Comment by SquareHeadd** [comment]
Yep I was a dumbass It's working thank you man. :+1: :heart: 
@sheddup

**Comment by sheddup** [comment]
I updated the build so it works with the new csgo update
