### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by Roulettinho** [Jire/Charlatano#58]
WARN: Failed to initialize native filesystem for Windows java.lang.RuntimeException: Could not find installation home path. Please make sure bin/idea.properties is present in the installation directory.

Everytime I launch this cheat it shows this and the cheat doesn't work in game

**Comment by sheddup** [comment]
try reinstalling JDK

**Comment by Roulettinho** [comment]
@sheddup Already tried, I can make a successful build now but this error is still occurring.

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/0.9.7
