### ISSUE TITLE
failed to initialize

### ISSUE THREAD

**Issue by firas500** [Jire/Charlatano#589]
WARN: Failed to initialize native filesystem for Windows
java.lang.RuntimeException: Could not find installation home path. Please make s
ure bin/idea.properties is present in the installation directory.
        at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.get
HomePath(PathManager.java:97)
        at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.fin
dBinFile(PathManager.java:173)
        at org.jetbrains.kotlin.com.intellij.util.lang.UrlClassLoader.loadPlatfo
rmLibrary(UrlClassLoader.java:320)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32.<cl
init>(IdeaWin32.java:48)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.getM
ediator(FileSystemUtil.java:77)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.<cli
nit>(FileSystemUtil.java:69)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.setFile
StampAndLength(ZipHandler.java:69)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.creat
eAccessor(ZipHandler.java:51)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.creat
eAccessor(ZipHandler.java:47)
        at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.createHan
dle(FileAccessorCache.java:66)
        at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.get(FileA
ccessorCache.java:52)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.getCach
edZipFileHandle(ZipHandler.java:112)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.createE
ntriesMap(ZipHandler.java:87)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ArchiveHandler.get
EntriesMap(ArchiveHandler.java:190)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarHandler
.<init>(CoreJarHandler.java:42)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSys
tem$1.create(CoreJarFileSystem.java:37)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSys
tem$1.create(CoreJarFileSystem.java:33)
        at org.jetbrains.kotlin.com.intellij.util.containers.FactoryMap.get(Fact
oryMap.java:58)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSys
tem.findFileByPath(CoreJarFileSystem.java:50)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.findJarRo
ot(KotlinCoreEnvironment.kt:359)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.contentRo
otToVirtualFile(KotlinCoreEnvironment.kt:340)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.access$co
ntentRootToVirtualFile(KotlinCoreEnvironment.kt:114)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$5.invoke(
KotlinCoreEnvironment.kt:223)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$5.invoke(
KotlinCoreEnvironment.kt:114)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertC
lasspathRoots(ClasspathRootsResolver.kt:70)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(Ko
tlinCoreEnvironment.kt:230)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(Ko
tlinCoreEnvironment.kt:114)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion
.createForProduction(KotlinCoreEnvironment.kt:409)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplChecker.<init>(GenericRe
plChecker.kt:63)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericR
eplCompiler.kt:53)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericR
eplCompiler.kt:51)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$r
eplCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:45)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$r
eplCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.g
etReplCompiler(KotlinJsr223JvmLocalScriptEngine.kt)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$l
ocalEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:51)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$l
ocalEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.g
etLocalEvaluator(KotlinJsr223JvmLocalScriptEngine.kt)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.g
etReplEvaluator(KotlinJsr223JvmLocalScriptEngine.kt:53)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.c
reateState(KotlinJsr223JvmLocalScriptEngine.kt:57)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.
createState$default(KotlinJsr223JvmScriptEngineBase.kt:46)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.
getCurrentState(KotlinJsr223JvmScriptEngineBase.kt:53)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.
nextCodeLine(KotlinJsr223JvmScriptEngineBase.kt:44)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.
compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:59)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.
eval(KotlinJsr223JvmScriptEngineBase.kt:31)
        at javax.script.AbstractScriptEngine.eval(Unknown Source)
        at com.charlatano.utils.Dojo.script(Dojo.kt:32)
        at com.charlatano.Charlatano.loadSettings(Charlatano.kt:69)
        at com.charlatano.Charlatano.main(Charlatano.kt:41)

**Comment by firas500** [comment]
up

**Comment by denizdeni** [comment]
what's your OS?

**Comment by denizdeni** [comment]
Move the charlatano folder to Desktop and run Start Charlatano.bat with Administrator Rights.

**Comment by firas500** [comment]
i"m on WIN7 x64 i'll try

**Comment by denizdeni** [comment]
download java jdk 8 and java jde 8

**Comment by firas500** [comment]
Fixed i had to install Windows 10 and it worked fine even the error still existed
