### ISSUE TITLE
Jire, any panorama updates?

### ISSUE THREAD

**Issue by newhope1992** [Jire/Charlatano#596]
It's not working for me since panorama came out, 
Are you gonna do any fixes  maybe? :D 👯‍♂️

**Comment by SnazzyMan-cpp** [comment]
check line 81 of CSGO.kt you can probs figure it out from there

**Comment by newhope1992** [comment]
Im not sure i know what are you refering too :/  Can't find it.
Im reading down there that 1.0.7 version is already made for panorama.
Guess i'll re-build it then and check it out. Is it not working only for me since panorama came out?

**Comment by newhope1992** [comment]
Acutally i've made it, just went to some oly issue posts and did it, thanks.

**Comment by Jire** [comment]
https://github.com/Jire/Charlatano/releases/tag/1.0.8
