### ISSUE TITLE
Possible issue?

### ISSUE THREAD

**Issue by Righteous** [Jire/Charlatano#61]
Whenever I try to launch the batch file I get this message:

http://image.prntscr.com/image/a33a86e309644439a2331221b531a308.png

Now I don't know if this is to be expected but doubt it as the cheat doesn't load. I have installed JDK 8 Update 21 aswell. I also tried deleting the capsule folder but nothing seems to be working.

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/0.9.7
