### ISSUE TITLE
canals

### ISSUE THREAD

**Issue by Baffy** [Jire/Charlatano#62]
cheat aint working on the new map canals
edit: does not work any more at all :(

**Comment by abc123itismeee** [comment]
Yep. I thought maybe the cheat would only be broken for aim because new bone IDs for the new models, but its all together broken, might be valve stepping up their anticheat?

**Comment by abc123itismeee** [comment]
@Jire also take a look at the PM I sent you on HF.

**Comment by kazijepan** [comment]
doesnt work , please help

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/0.9.7
