### ISSUE TITLE
Cheat not working after new update

### ISSUE THREAD

**Issue by SoapTheFLyingDragon** [Jire/Charlatano#63]
No scripts work anymore after the canals update please fix. thank you <3

**Comment by sheddup** [comment]
+1

**Comment by sumgui316** [comment]
+1

**Comment by kazijepan** [comment]
Please someone help me with this? After update cheat doesnt work

**Comment by sumgui316** [comment]
@kazijepan Well just play without cheats until they fix it. Ain't such of a big deal...

**Comment by TheHatMan98** [comment]
Don't use cheat fucking faggot

**Comment by sheddup** [comment]
Its fixed now

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/0.9.7
