### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Time-xg** [Jire/Charlatano#636]
I try to build it. But something went wrong.
It may be the problem of caching files downloaded from the server, but I don't know how to delete the cache.
Excuse me asking for your help, thank you.

* What went wrong:
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not download fastutil.jar (it.unimi.dsi:fastutil:7.1.0)
      > Could not get resource 'https://jcenter.bintray.com/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar'.
         > Could not GET 'https://jcenter.bintray.com/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar'.
            > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfront.net/13.32.16.186, d29vzk4ow07wi7.cloudfront.net/13.32.16.224, d29vzk4ow07wi7.cloudfront.net/13.32.16.112, d29vzk4ow07wi7.cloudfront.net/13.32.16.4] failed: Read timed out

**Comment by Primeknight19** [comment]
Oh got it. Sorry i dont know how to do that.

**Comment by Time-xg** [comment]
> Oh got it. Sorry i dont know how to do that. Wait for some minutes or hour somebody will reply this.

Thank you very much for your help. I tried to replace the Internet and solve the problem.
