### ISSUE TITLE
Does Charlatano work with FaceIT Premium?

### ISSUE THREAD

**Issue by Georgeforemangril** [Jire/Charlatano#64]
Kind of scared to try it because i don't have a second account i can play faceit with, plus i pay for faceit, so makes me abit wary.

If anyone has used Charlatano with faceit, would you be able to say what scripts to use and what scripts to not use?

Thank you! ^.^

**Comment by TheHatMan98** [comment]
stop use cheat! if you do that you don't need be scared!

**Comment by abc123itismeee** [comment]
wouldnt risk it tbh

**Comment by Jire** [comment]
Because it doesn't bypass object callbacks, it does not work in any FaceIT queues where the client is required. Charlatano does however completely bypass FaceIT's server-sided anti-cheat, so you can use it just fine if the client isn't open (for free queues).
