### ISSUE TITLE
Aimlock issue

### ISSUE THREAD

**Issue by Primeknight19** [Jire/Charlatano#643]
After the recent update on ' Proper Aim Flick Down Fix '. whenever i shoot someone my crosshair or aim gets stuck onto enemy around 3 second even after enemy die, i cant even move it, i already checked my settings, but nothing to do with aim lock or aim stickiness is enabled.

Please someone could fix these bug @Jire or @10urshin 
Thanks you

**Comment by 10urshin** [comment]
Can't be RCS. It wont make you lock on people. Try disabling rcs and see if it's still happening. If so post a short video showing the issue.

**Comment by Primeknight19** [comment]
maybe not RCS, something to do with aim stickiness, i will try disabling rcs, thanks for reply
