### ISSUE TITLE
Failed to initialize native filesystem for Windows

### ISSUE THREAD

**Issue by TheHatMan98** [Jire/Charlatano#66]
I get this error when i try to start charlatano "WARN: Failed to initialize native filesystem for Windows
java.lang.RuntimeException: Could not find installation home path. Please make s
ure bin/idea.properties is present in the installation directory."

I have reinstalled jdk and i have point  JAVA_HOME to where the JDK software is located , and reinstalled Charlatano? what should i do?

**Comment by Roulettinho** [comment]
Have same issue since 0.96 hotfix was released :/

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/0.9.7
