### ISSUE TITLE
press any key to continue...

### ISSUE THREAD

**Issue by bero17** [Jire/Charlatano#67]
Hey, i need help with V : 0.9.7 , i get a black screen then "press any key to continue..." 
if i press any key it closes , and i got the same problem with previous versions too . what to do ? .

**Comment by Austin72** [comment]
https://github.com/Austin72/CS-PRO

Use my build. It's better.

**Comment by DeathStrax** [comment]
How do I run  the hack

**Comment by Jire** [comment]
Try with [1.0.1](https://github.com/Jire/Charlatano/releases/tag/1.0.1)
