### ISSUE TITLE
Performance issues after todays ~30mb update

### ISSUE THREAD

**Issue by vaaski** [Jire/Charlatano#677]
As stated in the title, it stutters horribly and aim doesn't seem to be working. 1.0.9 update.

**Comment by LuanDevecchi** [comment]
it seems to be working only on local matches

**Comment by Saxheel** [comment]
Every game I played last night (without Char, haven't been using it since the BR update) was stuttery and horrible. I think it could be the servers as a result of the game going F2P.

**Comment by vaaski** [comment]
thanks @invinciblemeh, that solved it.

**Comment by Jire** [comment]
With the new 1.0.9 release the RCS should no longer cause stutter also :smile:
