### ISSUE TITLE
Aimbot only works on M4's and Ak

### ISSUE THREAD

**Issue by anthrax0227** [Jire/Charlatano#679]
im new to this hack so idk if its designed that way :/

**Comment by legithawle** [comment]
aimbot doesnt work at all OMEGALUL

**Comment by fonzy4567234** [comment]
yes doesnt work at all

**Comment by anthrax0227** [comment]
tried earlier, maybe i just got gud thinking im using hacks lol

**Comment by Jire** [comment]
It only is enabled for automatic weapons

**Comment by anthrax0227** [comment]
Thanks for the update! i was talking about the early release :)
