### ISSUE TITLE
Don't work!

### ISSUE THREAD

**Issue by ayejayc** [Jire/Charlatano#72]
Doesn't say anything when i launch the batch, followed the video 
and just nothing happens, tried running as admin but still nothing, help please!
also got the latest version

**Comment by ArkEcko** [comment]
Did it build?

**Comment by ayejayc** [comment]
Didn't say anything with first launch up, restarted my pc and it works but when using the bhop it automatically switches my weapons in game and makes me loose speed so doesn't do a clean hop, and i've unbinded space in game through console

**Comment by ayejayc** [comment]
Didn't say anything with first launch up, restarted my pc and it works but when using the bhop it automatically switches my weapons in game and makes me loose speed so doesn't do a clean hop, and i've unbinded space in game through console

**Comment by ayejayc** [comment]
Didn't say anything with first launch up, restarted my pc and it works but when using the bhop it automatically switches my weapons in game and makes me loose speed so doesn't do a clean hop, and i've unbinded space in game through console
