### ISSUE TITLE
compileKotlin FAILED

### ISSUE THREAD

**Issue by Feisser** [Jire/Charlatano#731]
I installed the Java SE Development Kit 8u191 for Windows x86 and start the build.bat but...

* What went wrong:
Execution failed for task ':compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_191' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

**Comment by 10urshin** [comment]
http://bfy.tw/LjA3
