### ISSUE TITLE
New Discord Link Please

### ISSUE THREAD

**Issue by zayidv** [Jire/Charlatano#802]
Happiness for this .. very good I would like to join the discord group who has the link ???

**Comment by Jire** [comment]
There is no more Discord because they keep banning me, sorry.

**Comment by zayidv** [comment]
> There is no more Discord because they keep banning me, sorry.


Thanks is an excellent job and I would like to receive updates and things related to your work.

I would like to receive an update 
and I would like to know if it can be used with faceit AC when I activate the AC does not work there is some way. thank you very much and excuse my bad english
