### ISSUE TITLE
 after today's update 30/04/2019 does not work

### ISSUE THREAD

**Issue by zayidv** [Jire/Charlatano#813]
@Jire after today's 30/04/2018 update does not work, or what should I do to make it work? 
please help and excuse my bad english

**Comment by Evilhelder** [comment]
yes.... don't work anymore....

**Comment by jasonlam00** [comment]
does not work anymore

**Comment by zayidv** [comment]
> does not work anymore

it will not work anymore 
or you just have to wait for jiru  fix it

**Comment by vaaski** [comment]
can confirm, wall and aim aren't working

**Comment by karmalegend** [comment]
Seems like they changed their memory adresses

**Comment by wholivesinapineappleunderthesea** [comment]
> 
> 
> Seems like they changed their memory adresses
> 
> Or maybe a new way to inject?

You don't inject external cheats...

**Comment by SnowManOnCoke** [comment]
does it work for some1 else?

**Comment by BroniDanson** [comment]
It will not work until offsets ( I might be wrong ) will get updatet, all cheats are now usless bc of the new csgo update

**Comment by zayidv** [comment]
Since yesterday evening and today I just finished solving thx  @AStupidRat 
it helped me a lot since I do not speak English last a long time to do it 
the solution is very simple you just have to read  
I'm not going to make them suffer I'll just tell them how they do not ask me to explain if they do not understand since I do not speak English

just copu and past it https://github.com/Jire/Charlatano/blob/50ca4e640021db9357b6248b003308b5af9afeb7/src/main/kotlin/com/charlatano/game/entity/EntityType.kt

paste in Charlatano/src/main/kotlin/com/charlatano/game/entity/EntityType.kt


and stop giving false speculation now works perfectly for me and always worked just read, I do not speak English thanks! enjoy
