### ISSUE TITLE
Not working??

### ISSUE THREAD

**Issue by Manny13221** [Jire/Charlatano#814]
Tried using today but esp or aim nothing works

**Comment by nghminh163** [comment]
fixed

**Comment by historia3** [comment]
> fixed

?

**Comment by SnowManOnCoke** [comment]
Still not working

**Comment by Manny13221** [comment]
> fixed
 still  not working for me

**Comment by BroniDanson** [comment]
Yeah csgo update messed up all hacks

**Comment by zayidv** [comment]
it work for me just read.

**Comment by cresoo** [comment]
> it work for me just read.

i added the 7 lines exactly as it shown , and still not working

**Comment by zayidv** [comment]
> i added the 7 lines exactly as it shown , and still not work

it no 7 lines -.- read my post the cheat work

**Comment by Manny13221** [comment]
fixed
