### ISSUE TITLE
Execution failed for task ':compileKotlin'.

### ISSUE THREAD

**Issue by GhostZ-AR** [Jire/Charlatano#816]
![cmd_dm2MpIBrVe](https://user-images.githubusercontent.com/38631917/57051205-4482cc80-6c35-11e9-8413-26639efd9741.png)
I get this error whenever I open build.bat. I seen that other people had similar issues and I tried to reinstall Java Platform (JDK) 12.0.1 (64-bit) and deleted the .gradle folder but I still get the same error.

**Comment by GhostZAR** [comment]
This is what my C:\Program Files\Java looks like:
![explorer_Qpfc2vOfAq](https://user-images.githubusercontent.com/38631917/57051348-f5896700-6c35-11e9-905a-3a6e03bccfcf.png)

**Comment by j3rr7** [comment]
![57051205-4482cc80-6c35-11e9-8413-26639efd9741](https://user-images.githubusercontent.com/29926331/57052976-1c3ab280-6cb5-11e9-93a2-fde6108e9f7e.png)
learn to read

**Comment by j3rr7** [comment]
1. download java, download jdk 
java 
https://www.java.com/en/download/
jdk
https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
or
1. change ur PATH folder

**Comment by GhostZ-AR** [comment]
I already have the latest version of Java and JDK.

**Comment by ffauzan** [comment]
JDK and JRE should have the same version. Check in C:\Program Files\Java

**Comment by GhostZ-AR** [comment]
This is what I have in C:\Program Files\Java
![explorer_3VcifMVyv8](https://user-images.githubusercontent.com/38631917/57055235-f24ea500-6c4e-11e9-863f-1835f0a006db.png)

**Comment by kalilc** [comment]
Sometimes i got this error trying to compile as admin, try not admin. 

Also i fixed other compile problems with this:
Right click in the start menu (windows logo) > open powershell as admin > navigate to charlatano folder ( cd "path") and type .\build.bat

**Comment by GhostZ-AR** [comment]
I right click the build.bat file and pressed open, I also tried to Run as Administrator but that caused another error. I'll try the other fix later.

**Comment by ffauzan** [comment]
> This is what I have in C:\Program Files\Java
> ![explorer_3VcifMVyv8](https://user-images.githubusercontent.com/38631917/57055235-f24ea500-6c4e-11e9-863f-1835f0a006db.png)

Uninstall all of your jre and jdk. Install new jre and jdk with the same version. Different version between jre and jdk confused the gradle.

**Comment by GhostZ-AR** [comment]
Where do I find older versions of JDK?

**Comment by GhostZ-AR** [comment]
> > This is what I have in C:\Program Files\Java
> > ![explorer_3VcifMVyv8](https://user-images.githubusercontent.com/38631917/57055235-f24ea500-6c4e-11e9-863f-1835f0a006db.png)
> 
> Uninstall all of your jre and jdk. Install new jre and jdk with the same version. Different version between jre and jdk confused the gradle.
> ![image](https://user-images.githubusercontent.com/32434534/57111612-038ad500-6d67-11e9-83be-ddf59828d4ae.png)

Thanks! This fixed the issue.
