### ISSUE TITLE
Does this hack work on faceit?

### ISSUE THREAD

**Issue by SerVigor** [Jire/Charlatano#837]
It has the faceit mode but does it bypass the faceit anticheat?

**Comment by Loobo1** [comment]
what i heard its not detected but its hard to get it started

**Comment by SerVigor** [comment]
May I ask how it gets started?

**Comment by SerVigor** [comment]
I'm planning to only use path aim & bhop script, also does the esp work?

**Comment by Loobo1** [comment]
idk. just heard from others it works but its hard to get started cus faceit client blocks it

**Comment by SerVigor** [comment]
Yeah just tried the hack didn't even inject can you give me their username or ask them for me?
