### ISSUE TITLE
Will user data be submitted to Valve ?

### ISSUE THREAD

**Issue by dev1ces** [Jire/Charlatano#851]
<img width="655" alt="屏幕快照 2019-07-15 上午8 44 57" src="https://user-images.githubusercontent.com/45646273/61191427-2fb6c080-a6dd-11e9-919d-63e3df79fc42.png">

I donated your project, but you submitted user data to Valve?
Maybe one day Valve will ban everyone.

**Comment by 0-x-2-2** [comment]
🤡

**Comment by ffauzan** [comment]
What do you mean? The users are submitting this cheat to valve. 
You can see the source code, and this cheats not sending any data anywhere.

**Comment by dev1ces** [comment]
> What do you mean? The users are submitting this cheat to valve.
> You can see the source code, and this cheats not sending any data anywhere.

It's not users, it's developer jire.

**Comment by ffauzan** [comment]
> > What do you mean? The users are submitting this cheat to valve.
> > You can see the source code, and this cheats not sending any data anywhere.
> 
> It's not users, it's developer jire.

You misunderstand what Jire means in that post.

**Comment by dev1ces** [comment]
> > > What do you mean? The users are submitting this cheat to valve.
> > > You can see the source code, and this cheats not sending any data anywhere.
> > 
> > 
> > It's not users, it's developer jire.
> 
> You misunderstand what Jire means in that post.

Maybe, if I misunderstand it, I will continue to Donate.

**Comment by 10urshin** [comment]
Yes jire is employed by valve right now because of this /s

**Comment by dev1ces** [comment]
> Yes jire is employed by valve right now because of this /s

What !!??Is that still safe?

**Comment by tamal777** [comment]
Only 82 upvotes. Ohhhh okkkkkkk
