### ISSUE TITLE
I cant find the place to run Charlatano

### ISSUE THREAD

**Issue by Shatterz-png** [Jire/Charlatano#875]
There arent any places I've looked inside the master that let me run Charlatano? Any ideas where it could be?

**Comment by Shatterz-png** [comment]
*found it

**Comment by Ariarad** [comment]
Don’t worry .. go at “release” and downlaod the charlatano (64 Mb ) then run the bat file ( Start Charlatano 1.0.11 ) that’s it 😉

Sent from Mail for Windows 10

From: Shatterz-png
Sent: Saturday, December 7, 2019 9:23 PM
To: Jire/Charlatano
Cc: Subscribed
Subject: [Jire/Charlatano] I cant find the place to run Charlatano (#875)

There arent any places I've looked inside the master that let me run Charlatano? Any ideas where it could be?
