### ISSUE TITLE
ESP - GLOW 

### ISSUE THREAD

**Issue by kominxe** [Jire/Charlatano#91]
GLOW IN ESP WORKING FOR SOMEBODY?

**Comment by M4jx** [comment]
Same here.
OpenGL is not working in the background when i start the cheat.

**Comment by mountaser** [comment]
its bez u r a big noob @M4jx

**Comment by kominxe** [comment]
In 9.8 glow working fine, opengl - black screen. In 1.0 no glow, and black opengl overlay.

**Comment by Alexw0wTV** [comment]
can i still you 0.98 without ban?
