### ISSUE TITLE
As of today, not working for me RIP..

### ISSUE THREAD

**Issue by newhope1992** [Jire/Charlatano#925]
Started it today, nothing,
updated java just in case, and jdk, nothing,
downaloaded 1.0.11 again, did everything like it's supposed to be, nothing.

RIP....
Anyone else having problems? Csgo offset update?

**Comment by vokisking** [comment]
Offset update

**Comment by effingnoone** [comment]
in advanced.kts change to CLIENT_MODULE_NAME = "client.dll" 
actually update changed client_panorama.dll to client.dll

**Comment by vokisking** [comment]
> in advanced.kts change to CLIENT_MODULE_NAME = "client.dll"
> actually update changed client_panorama.dll to client.dll

Thanks man, apreciatte it.

**Comment by newhope1992** [comment]
OH! IT ACTUALLY WORKED!

Simple fix, you are the real MVP man. Cheers.

**Comment by joeyli02** [comment]
How do you change the client_panorama.dll to client.dll do you rename it or something cause I see both of them in my ( C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\bin )
