### ISSUE TITLE
haw to fixit?

### ISSUE THREAD

**Issue by jbgnece** [Jire/Charlatano#928]

**Comment by effingnoone** [comment]
in advanced.kts change to CLIENT_MODULE_NAME = "client.dll" 
actually update changed client_panorama.dll to client.dll

**Comment by jbgnece** [comment]
> in advanced.kts change to CLIENT_MODULE_NAME = "client.dll"
> actually update changed client_panorama.dll to client.dll

and thats all?

**Comment by jbgnece** [comment]
> in advanced.kts change to CLIENT_MODULE_NAME = "client.dll"
> actually update changed client_panorama.dll to client.dll

its not working

**Comment by effingnoone** [comment]
> > in advanced.kts change to CLIENT_MODULE_NAME = "client.dll"
> > actually update changed client_panorama.dll to client.dll
> 
> its not working

Working for me and those who did the same thing. Check what you are changing.

**Comment by newhope1992** [comment]
OH! IT ACTUALLY WORKED!

Simple fix, you are the real MVP man. Cheers.

**Comment by jbgnece** [comment]
working thx man

**Comment by pie4sy** [comment]
Ay thank you sm man
