### ISSUE TITLE
Aim bot going crazy.

### ISSUE THREAD

**Issue by Myth80** [Jire/Charlatano#937]
Okay so I've just encountered this problem today. When I press my force aim key and the aimbot is within the FOV, the aimbot goes wild. It jumps up to almost sky level and then comes back down to the ground and then goes back to the head. Whenever I try to shoot without force aim , the crosshair starts going side ways like crazy and then starts following the target perfectly. My cfgs are almost the same as given in the build.

**Comment by sotakoira** [comment]
That's an issue with most recent CSGO update. Just wait for a fix.

**Comment by TheFuckingRat** [comment]
Use flat aim, latest update breaks game sensitivity which path aim relies on.

**Comment by Jire** [comment]
Should be fixed in https://github.com/Jire/Charlatano/releases/tag/1.0.12

**Comment by Myth80** [comment]
> Should be fixed in https://github.com/Jire/Charlatano/releases/tag/1.0.12
Path aim still doesn't work. Still does the same thing.

**Comment by Myth80** [comment]
> Should be fixed in https://github.com/Jire/Charlatano/releases/tag/1.0.12

Path aim still doesn't work.Still does the same thing.
