### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Ariarad** [Jire/Charlatano#959]
dude RATTO do u have Masochism or sth ?! why did u get me ban on discord? i didn't even speak with u guys and I was just following the updates and issues, pls dont be a 30yo kid and send me the link.

**Comment by siautalius** [comment]
masochism the tendency to derive sexual gratification from one's own pain or humiliation.
sounds hot

**Comment by thefuckingrap** [comment]
stfu loser

**Comment by retart1337** [comment]
1

**Comment by retart1337** [comment]
You wasn't banned, discord server just was tapped by mods
here is updated invite link
https://discord.gg/xkTteTM

**Comment by retart1337** [comment]
And also can you give your discord tag to inform you about future problems?

**Comment by Ariarad** [comment]
> You wasn't banned, discord server just was tapped by mods
> here is updated invite link
> https://discord.gg/xkTteTM

appreciate that 👍

**Comment by Ariarad** [comment]
> And also can you give your discord tag to inform you about future problems?

sure, here u r AriA-#0214

**Comment by dusty-dusty** [comment]
> 
> 
> You wasn't banned, discord server just was tapped by mods
> here is updated invite link
> https://discord.gg/xkTteTM

what is the new link that one does not work again
