### ISSUE TITLE
Settings are hardcoded, Box esp and Skeleton esp are not working

### ISSUE THREAD

**Issue by csirketorta** [Jire/Charlatano#978]
Hi there!
Well... Title says all tbh.
I cannot load my settings stored in the settings folder, it only applies when I rebuild the cheat itself.
Also, it's crashing when I'm trying to enable box or skeleton esp, see below.
![error](https://user-images.githubusercontent.com/46249257/103148092-5e531a80-475c-11eb-9c1b-250412789b99.png)

1.0.12 works just fine, but I hope this will get fixed soon.
Some system specifications:
Windows 10 Pro H2
JRE 8u271 (64 bit)
JDK 11.0.9 (64 bit)

**Comment by csirketorta** [comment]
It is still broken with 1.1.3.
https://imgur.com/a/mUMIwut

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/1.1.4
