### ISSUE TITLE
How i can desactivate glow esp for team8's & enemies?

### ISSUE THREAD

**Issue by Mani-Dd** [Jire/Charlatano#981]
I already placed evcerything in FALSE at the ESP.kts also at SCRIPTS.kts
but glow is always there, how can i desactivate it? 
help.

**Comment by csirketorta** [comment]
The cheat is broken right now, it does not read the settings file properly even though it has been "fixed" already, yet its still broken.

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/1.1.4
