### ISSUE TITLE
I require help with settings and an error message

### ISSUE THREAD

**Issue by iamnotproudofmyself** [Jire/Charlatano#982]
Every time I double click on the .bat file the command prompt displays the messages shown in the screenshot. Also, the program ignores all changes to the settings and always launches with defaults, recoil enabled, glow esp enabled which doesn't show opponents through walls and so on. Any help is appreciated, cheers.
![Screenshot_1](https://user-images.githubusercontent.com/76733771/103284388-91174000-49f4-11eb-8835-32eaf983a60d.png)

**Comment by Jire** [comment]
Let me know if fixed in https://github.com/Jire/Charlatano/releases/tag/1.1.3

**Comment by Jire** [comment]
Fixed in https://github.com/Jire/Charlatano/releases/tag/1.1.4
