### ISSUE TITLE
Problem with the new update

### ISSUE THREAD

**Issue by mariusflorin15** [Jire/Charlatano#983]
When i start i receive an error

https://i.gyazo.com/ea056bf665120c4e4d10791cc2bde754.png

Here is the error, i try download just release and al source code to use build.bat file but it's the same error

**Comment by csirketorta** [comment]
Yep, same error.

**Comment by csirketorta** [comment]
PS.: @Jire if you could share us a contact link, that would be appreciated.

**Comment by Ultimate132** [comment]
I'm having the same error I'm waiting for it to resolve and I'm using the July version that is working!

**Comment by Jire** [comment]
Should be fixed in https://github.com/Jire/Charlatano/releases/tag/1.1.4
