### ISSUE TITLE
how to resolve?

### ISSUE THREAD

**Issue by apidotmy** [Jire/Charlatano#984]
![Screenshot_2](https://user-images.githubusercontent.com/25004320/103306565-d06f7c00-4a48-11eb-96c3-72c4f40a3dfe.png)

**Comment by SnowManOnCoke** [comment]
Yea i have the same error dont know how to fix it xD i am trying to solve it for like 3 hours

**Comment by apidotmy** [comment]
> Yea i have the same error dont know how to fix it xD i am trying to solve it for like 3 hours

Hhhhh me too bruh :v

**Comment by Jire** [comment]
Let me know if fixed in #1.1.4

**Comment by apidotmy** [comment]
> Let me know if fixed in [1.1.4](https://github.com/Jire/Charlatano/releases/tag/1.1.4)

Letme try. Wait

**Comment by SnowManOnCoke** [comment]
that problem is fixed but i get another one "an illegal reflective access operation has occurred" how can i solve this one?

**Comment by Jire** [comment]
> that problem is fixed but i get another one "an illegal reflective access operation has occurred" how can i solve this one?

that's just a warning and shouldn't effect anything

**Comment by SnowManOnCoke** [comment]
oh okay thanks good job

**Comment by apidotmy** [comment]
> Let me know if fixed in [1.1.4](https://github.com/Jire/Charlatano/releases/tag/1.1.4)

Nice bruh. Its work perfect for me. Muach
