### ISSUE TITLE
1.1.4 problems glow esp windows 7 Ultimate ESU x64 

### ISSUE THREAD

**Issue by nix9191** [Jire/Charlatano#989]
Hi the cheat with the new update is broken now the glow_esp  show  both teams but i dont see enemy through wall  and when i change setting etc not working and the aim sometimes is not working the glow is not same from 1.0.12 . right now i use again 1.0.12 version dont have problems in windows 7 Ultimate extended support updates(ESU)  . and i see people have also problems in windows 10 with 1.1.4 .....
I hope Jire will add skin changer in this cheat ...
And i want to say that Jire is the best  thank you to share us this awesome cheat i hope you fix this bug from 1.14

**Comment by Jire** [comment]
Let me know if fixed in [1.1.5](https://github.com/Jire/Charlatano/releases/tag/1.1.5)

**Comment by nix9191** [comment]
> Let me know if fixed in [1.1.5](https://github.com/Jire/Charlatano/releases/tag/1.1.5)

yes it works the glow esp is the same from 1.0.12 thank you very much Jire and also works in windows 10 last version and windows 7 ultimate i hope you add skin changer from abendigo to charlatano
