### ISSUE TITLE
1.20 bug aim not always working 

### ISSUE THREAD

**Issue by nix9191** [Jire/Charlatano#994]
Hi Jire is seems that 1.20 have problem with aim not working every time  in competitive matchmaking i try the old version is working fine but with new update 1.20 is not always working is slower i try to change the settings for better aim still have this issue

**Comment by Jire** [comment]
It's due to read caching, which reduces CPU usage. You can set it to a lower value in `Advanced.kts` with the `CACHE_EXPIRE_MILLIS` variable.

I recommend 1ms to replicate the old behavior.

```kotlin
CACHE_EXPIRE_MILLIS = 1L
```

**Comment by Jire** [comment]
The above is no longer necessary, as aim speed scaling based on `CACHE_EXPIRE_MILLIS` has been added in version [1.2.1](https://github.com/Jire/Charlatano/releases/tag/1.2.1)
